"""
Complaint Triage Orchestrator -- business dashboard (spec Section 10, Phase 6).

Reads dashboard/data/pipeline_log.json, generated by
scripts/export_dashboard_data.mjs from the ACTUAL committed n8n workflow --
this file computes and displays, it does not invent any pipeline logic of
its own.

Data honesty note (read before extending this file): as of this build, only
tickets with hand-verified fixture data (spec Section 6's original three,
plus any added since) have a genuine pipeline decision -- Phase 7's
mock-to-real Claude API swap hasn't happened, so every other live ticket the
Schedule/Manual trigger fetches still dead-ends. This dashboard is built to
show that real, small n honestly (see EMPTY-STATE COPY below) rather than
pad the log with invented tickets to make charts look fuller. When a real
pilot run accumulates more records, this same code renders them -- nothing
here assumes an exact count.

Run: streamlit run dashboard/app.py
"""

import json
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st
import streamlit.components.v1 as components


def md_html(s: str):
    """st.markdown(unsafe_allow_html=True), but with every line's leading
    whitespace stripped first.

    Markdown treats any line indented 4+ spaces as a preformatted code
    block, independent of unsafe_allow_html -- HTML built from f-strings at
    Python nesting depth (every block in this file) trips that rule and
    renders as literal escaped tags instead of markup. textwrap.dedent()
    alone isn't enough here: it only strips the whitespace common to every
    line, but this file assembles HTML by concatenating fragments built at
    different nesting depths (e.g. table rows built inside a loop, then
    joined into a table built in the caller), so no single common prefix
    covers every line. Stripping per-line instead guarantees no line can
    trip the 4-space rule, regardless of which function contributed it.
    """
    st.markdown("\n".join(line.lstrip() for line in s.split("\n")), unsafe_allow_html=True)

# ---------------------------------------------------------------------------
# Brand palette (Leo_Chan_Brand_Identity.md, spec Section 10 -- exact values,
# not approximated).
# ---------------------------------------------------------------------------
NAVY = "#153E75"
SLATE = "#475569"
LIGHT_GREY = "#E5E7EB"
BACKGROUND = "#F8FAFC"
WHITE = "#FFFFFF"
# A small tint scale off Navy for chart series -- the brand system says
# "avoid bright colours," so chart series are navy-family, not a rainbow.
CHART_SERIES = [NAVY, "#3D6FB3", "#7FA3D1", SLATE, "#94A3B8"]

# Agent roles (spec Section 6) -- referenced both in chart labels (so a bar
# or bar-group is self-explanatory without hovering) and in the persistent
# legend rendered at the top of the Technical detail tab (so it doesn't
# depend on a viewer noticing the chart labels at all).
AGENT_INFO = {
    1: {"name": "Classification", "tool": "Regulatory taxonomy lookup", "used_when": "Only when the narrative is ambiguous relative to the filed category"},
    2: {"name": "Research", "tool": "Synthetic CRM lookup + regulation-text lookup", "used_when": "Regulation lookup always; special-population check always; broader CRM context only when relevant"},
    3: {"name": "Drafting", "tool": "Exact regulation clause fetch", "used_when": "Only when citing a specific provision"},
    4: {"name": "QA / escalation-scoring", "tool": "Re-verify a cited clause or CRM fact", "used_when": "Only when the draft makes a checkable claim"},
}

DATA_PATH = Path(__file__).resolve().parent / "data" / "pipeline_log.json"

st.set_page_config(page_title="Complaint Triage Orchestrator", layout="wide", page_icon=None)


# ---------------------------------------------------------------------------
# Styling -- none of this works out of the box in Streamlit (spec Section 10).
# ---------------------------------------------------------------------------
def inject_brand_css():
    md_html(
        f"""
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@600;700&family=Inter:wght@400;500&display=swap');

        html, body, [class*="css"] {{
            font-family: 'Inter', sans-serif;
            color: {SLATE};
            background-color: {BACKGROUND};
        }}
        h1, h2, h3, h4, .kpi-label {{
            font-family: 'Manrope', sans-serif;
            font-weight: 600;
            color: {NAVY};
        }}
        .stApp {{
            background-color: {BACKGROUND};
        }}

        /* Hide Streamlit's default chrome -- the single biggest tell an
           app wasn't designed (spec Section 10). */
        #MainMenu {{ visibility: hidden; }}
        footer {{ visibility: hidden; }}
        header {{ visibility: hidden; }}
        div[data-testid="stToolbar"] {{ visibility: hidden; }}

        /* Cap content width -- default edge-to-edge layout reads unstyled. */
        .block-container {{
            max-width: 1180px;
            padding-top: 2rem;
            padding-bottom: 2rem;
        }}

        /* KPI cards: custom HTML/CSS, not st.metric (spec explicit) --
           white background, thin light-grey border, Manrope small-caps
           label, large Inter Medium navy number. */
        .kpi-card {{
            background: {WHITE};
            border: 1px solid {LIGHT_GREY};
            border-radius: 8px;
            padding: 1.1rem 1.2rem;
            height: 100%;
            /* `height: 100%` alone doesn't equalize these across the row --
               Streamlit's own internal wrappers between st.columns()'s flex
               row and this card (an unnamed centering div with
               align-items: center among them) don't propagate height:100%
               down the chain, so each card still shrinks to its own content
               (verified live: 126px-197px across the 5 cards depending on
               sub-label length). A min-height sized to the longest current
               sub-label (Escalation agreement's 4-line text) is a simpler,
               more robust fix than fighting undocumented internal DOM. */
            min-height: 200px;
        }}
        .kpi-label {{
            font-size: 0.72rem;
            font-weight: 600;
            letter-spacing: 0.06em;
            text-transform: uppercase;
            color: {SLATE};
            margin-bottom: 0.5rem;
        }}
        .kpi-value {{
            font-family: 'Inter', sans-serif;
            font-weight: 500;
            font-size: 1.9rem;
            color: {NAVY};
            line-height: 1.1;
        }}
        .kpi-value.pending {{
            font-size: 1.05rem;
            font-weight: 500;
            color: {SLATE};
        }}
        .kpi-sub {{
            font-size: 0.74rem;
            color: {SLATE};
            margin-top: 0.35rem;
        }}

        /* Persistent (always rendered, no dismiss control), but NOT pinned
           to the viewport -- a fixed-position banner stayed visible while
           scrolling in a way that read as demanding attention rather than
           just disclosing. A normal block at the end of the page content
           is still persistent in the sense the spec means (can't be
           dismissed, always present), just not glued to the screen. */
        .disclosure-banner {{
            background: {SLATE};
            color: {WHITE};
            font-size: 0.8rem;
            padding: 0.65rem 1.5rem;
            border-radius: 6px;
            text-align: center;
            margin-top: 2rem;
        }}

        .queue-table {{
            width: 100%;
            border-collapse: collapse;
            font-size: 0.86rem;
        }}
        .queue-table th {{
            text-align: left;
            font-family: 'Manrope', sans-serif;
            font-weight: 600;
            font-size: 0.72rem;
            text-transform: uppercase;
            letter-spacing: 0.04em;
            color: {SLATE};
            border-bottom: 1px solid {LIGHT_GREY};
            padding: 0.5rem 0.6rem;
        }}
        .queue-table td {{
            border-bottom: 1px solid {LIGHT_GREY};
            padding: 0.6rem 0.6rem;
            vertical-align: top;
            color: {SLATE};
        }}
        .queue-table td.mono {{
            font-family: monospace;
            color: {NAVY};
        }}
        .section-caption {{
            font-size: 0.82rem;
            color: {SLATE};
            margin-top: -0.5rem;
            margin-bottom: 1rem;
        }}

        /* Agent legend -- persistent reference for what "Agent 1/2/3/4" mean. */
        .agent-legend {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 0.75rem;
            margin-bottom: 1.5rem;
        }}
        .agent-card {{
            background: {WHITE};
            border: 1px solid {LIGHT_GREY};
            border-left: 3px solid {NAVY};
            border-radius: 6px;
            padding: 0.75rem 0.9rem;
        }}
        .agent-card-num {{
            font-family: 'Manrope', sans-serif;
            font-weight: 600;
            font-size: 0.72rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: {SLATE};
        }}
        .agent-card-name {{
            font-family: 'Manrope', sans-serif;
            font-weight: 700;
            font-size: 1rem;
            color: {NAVY};
            margin: 0.15rem 0 0.4rem 0;
        }}
        .agent-card-tool {{
            font-size: 0.78rem;
            color: {SLATE};
            margin-bottom: 0.3rem;
        }}
        .agent-card-when {{
            font-size: 0.74rem;
            color: {SLATE};
            font-style: italic;
        }}

        /* A multiselect with every option already picked (e.g. the category
           filter with both categories selected) pops open to an empty "No
           results" list on click -- there's genuinely nothing left to add,
           so the message just reads as clutter. Hide it globally; no
           dropdown in this dashboard needs it. */
        [data-testid="stSelectboxVirtualDropdownEmpty"] {{ display: none !important; }}

        /* Queue card: the segmented control re-skinned as tabs attached
           directly to its table, not a separate widget floating above it
           (spec-adjacent UX fix -- Streamlit's default segmented_control is
           a standalone pill-button group with no way to visually attach it
           to what it controls). One bordered white card holds the tab
           strip and the table; the active tab's white background matches
           the card body below it so it reads as "open," while the inactive
           tab sits on the strip's grey background and looks receded. */
        .st-key-queue_card {{
            background: {WHITE};
            border: 1px solid {LIGHT_GREY};
            border-radius: 8px;
            overflow: hidden;
        }}
        .st-key-queue_card .stElementContainer {{ margin-bottom: 0 !important; }}
        /* The segmented_control's own element-container ships with an
           inline shrink-to-fit width (its content's natural size, e.g.
           ~220px) rather than stretching to the card -- override so the
           tab strip actually spans full width instead of sitting stranded
           in the top-left corner. */
        .st-key-queue_card .st-key-queue_view {{ width: 100% !important; }}
        .st-key-queue_card [data-testid="stButtonGroup"] {{
            display: flex;
            width: 100%;
            background: {BACKGROUND};
            border-bottom: 1px solid {LIGHT_GREY};
        }}
        /* Both buttons actually share ONE wrapper div (not one each) as the
           real flex child of stButtonGroup -- and that wrapper ships with
           Streamlit's own `max-width: fit-content`, which caps it at its
           content's natural size and defeats flex-grow before it can do
           anything. Override the cap, then let the buttons (real flex
           items of THIS wrapper) split its width evenly. */
        .st-key-queue_card [data-testid="stButtonGroup"] > div {{
            flex: 1 1 0;
            max-width: none !important;
            width: 100%;
        }}
        .st-key-queue_card [data-testid^="stBaseButton-segmented_control"] {{
            flex: 1 1 0;
            min-width: 0;
            border: none !important;
            border-radius: 0 !important;
            background: transparent !important;
            box-shadow: none !important;
            color: {SLATE} !important;
            font-family: 'Manrope', sans-serif !important;
            font-weight: 600 !important;
            font-size: 0.85rem !important;
            padding: 0.75rem 0.4rem !important;
            margin: 0 !important;
            white-space: normal !important;
            overflow: visible !important;
            text-overflow: clip !important;
        }}
        /* Exact (not prefix) match -- only the inactive-tab testid, so this
           doesn't fight the active tab's own white background on hover.
           The click already registers across the button's full box (it's a
           real <button> spanning the whole tab cell, verified live), but
           without this there was no visual feedback confirming that away
           from the centered text, which reads as "only the label is
           clickable" even though the whole area always was. */
        .st-key-queue_card [data-testid="stBaseButton-segmented_control"]:hover {{
            background: rgba(21, 62, 117, 0.06) !important;
            color: {NAVY} !important;
        }}
        .st-key-queue_card [data-testid^="stBaseButton-segmented_control"] * {{
            white-space: normal !important;
            overflow: visible !important;
            text-overflow: clip !important;
            text-align: center !important;
        }}
        .st-key-queue_card [data-testid="stBaseButton-segmented_controlActive"] {{
            background: {WHITE} !important;
            color: {NAVY} !important;
            box-shadow: inset 0 -3px 0 0 {NAVY} !important;
        }}
        .st-key-queue_card .stElementContainer:not(:has([data-testid="stButtonGroup"])) {{
            padding: 0.9rem 1.25rem 1.25rem;
        }}
        .st-key-queue_card .queue-table {{ margin: 0; }}
        .st-key-queue_card h4:first-child {{ margin-top: 0; }}
        </style>
        """
    )


def plotly_brand_layout(fig: go.Figure, title: str) -> go.Figure:
    fig.update_layout(
        title=dict(text=title, font=dict(family="Manrope, sans-serif", size=14, color=NAVY)),
        font=dict(family="Inter, sans-serif", size=12, color=SLATE),
        plot_bgcolor=WHITE,
        paper_bgcolor=WHITE,
        margin=dict(l=10, r=10, t=40, b=10),
        legend=dict(font=dict(family="Inter, sans-serif", size=11)),
    )
    fig.update_xaxes(showline=True, linecolor=LIGHT_GREY, gridcolor=LIGHT_GREY)
    fig.update_yaxes(showline=True, linecolor=LIGHT_GREY, gridcolor=LIGHT_GREY)
    return fig


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
@st.cache_data
def load_pipeline_log():
    if not DATA_PATH.exists():
        return None
    with open(DATA_PATH, encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# KPI computation (spec Section 9's five metrics). Each function documents
# WHY it either returns a real number from the log or an honest "not yet
# measurable" state -- no metric here is invented to fill a card.
# ---------------------------------------------------------------------------
def kpi_hours_saved():
    # Spec Section 9: "only the pipeline's own processing time still awaits
    # a real measurement at Phase 7" -- this build has never run against a
    # real, timed production schedule, only a manually-invoked test
    # harness. Reporting a number here would be fabricating exactly the
    # kind of figure this project has spent five phases refusing to fake.
    return None, "real pipeline timing (manual baseline: ~10 min/ticket, sourced)"


def kpi_sla_compliance():
    # Same reasoning as hours saved: "draft ready inside the 15-day window"
    # requires a real elapsed-time measurement from an actual production
    # run, which doesn't exist yet -- only manual test-harness executions.
    return None, "real pipeline timing measurement"


def kpi_citation_accuracy(records):
    # Real, computed: for every ticket where Agent 3 cited a regulation,
    # did the exact-clause-fetch tool actually resolve it against the
    # cached, real regulation corpus? This is QA-verified, not
    # self-reported -- Agent 3's and Agent 4's tool_result.found both come
    # from independent real lookups (see README's regulation-search
    # limitation note for the ceiling this implies).
    cited = [r for r in records if r["agents"]["agent3"]["tool_used"]]
    if not cited:
        return None, "No drafts cited a regulation yet"
    correct = sum(1 for r in cited if (r["agents"]["agent3"]["tool_result"] or {}).get("found"))
    pct = round(100 * correct / len(cited))
    return pct, f"{correct}/{len(cited)} cited drafts, QA-verified against real regulation text"


def kpi_escalation_agreement(records):
    # Real, computed -- and expected to read low here. See README/spec
    # Section 8: CFPB's own outcome category is a coarse administrative
    # label, not a severity judgment, so low agreement on this fixture set
    # is a demonstration of the metric's own honest limits, not a pipeline
    # defect. Never report this as accuracy.
    with_gt = [r for r in records if r.get("ground_truth")]
    if not with_gt:
        return None, "No ground-truth comparisons yet"
    agree = sum(1 for r in with_gt if r["ground_truth"]["agrees_with_ground_truth"])
    pct = round(100 * agree / len(with_gt))
    return pct, f"{agree}/{len(with_gt)} agree with CFPB's outcome fields — directional signal, not accuracy (Section 8)"


def kpi_category_agreement(records):
    # Real, computed: does Agent 1's classified issue match what the
    # consumer actually filed with CFPB, at either the issue or sub-issue
    # level (Ticket C's classification lands at the sub-issue level, since
    # that's the substantive category for that compound ticket -- see
    # spec Section 6).
    if not records:
        return None, "No classifications yet"
    matches = 0
    for r in records:
        out = r["agents"]["agent1"]["output"] or {}
        classified = out.get("primary_issue") or out.get("issue")
        if classified and classified in (r.get("issue"), r.get("sub_issue")):
            matches += 1
    pct = round(100 * matches / len(records))
    return pct, f"{matches}/{len(records)} match CFPB's own filed product/issue category"


def render_kpi_card(col, label, value, sub):
    with col:
        if value is None:
            value_html = '<div class="kpi-value pending">Awaiting Phase 7</div>'
            sub_html = f'<div class="kpi-sub">{sub}</div>'
        else:
            value_html = f'<div class="kpi-value">{value}%</div>'
            sub_html = f'<div class="kpi-sub">{sub}</div>'
        md_html(
            f"""
            <div class="kpi-card">
                <div class="kpi-label">{label}</div>
                {value_html}
                {sub_html}
            </div>
            """
        )


# ---------------------------------------------------------------------------
# Charts
# ---------------------------------------------------------------------------
def chart_decision_breakdown(records):
    counts = {"Escalated to human": 0, "Auto-resolved": 0}
    for r in records:
        if r["decision"] == "ESCALATE_TO_HUMAN":
            counts["Escalated to human"] += 1
        else:
            counts["Auto-resolved"] += 1
    fig = go.Figure(
        go.Bar(
            x=list(counts.keys()),
            y=list(counts.values()),
            marker_color=[NAVY, "#94A3B8"],
            text=list(counts.values()),
            textposition="outside",
            width=0.5,
        )
    )
    fig.update_layout(yaxis=dict(dtick=1))
    return plotly_brand_layout(fig, "Escalate vs. auto-resolve")


def chart_category_breakdown(records, selected=None):
    counts = {}
    for r in records:
        counts[r["product"]] = counts.get(r["product"], 0) + 1
    labels = list(counts.keys())
    base_colors = dict(zip(labels, CHART_SERIES))
    # PREVIEW ONLY (not yet wired to KPIs/other charts/tables): dims any
    # category not in `selected` -- empty/None selected means "all", so
    # nothing dims.
    if selected:
        colors = [base_colors[l] if l in selected else LIGHT_GREY for l in labels]
    else:
        colors = [base_colors[l] for l in labels]
    fig = go.Figure(
        go.Pie(
            labels=labels,
            values=list(counts.values()),
            marker=dict(colors=colors),
            hole=0.55,
            textfont=dict(family="Inter, sans-serif"),
        )
    )
    return plotly_brand_layout(fig, "Product category breakdown")


def chart_confidence_distribution(records):
    fig = go.Figure()
    for i, agent_key in enumerate(["agent1", "agent4"]):
        agent_num = 1 if agent_key == "agent1" else 4
        label = f"Agent {agent_num}"
        values, labels = [], []
        for r in records:
            out = r["agents"][agent_key]["output"] or {}
            conf = out.get("confidence")
            if conf is None and "issues" in out:
                # Ticket C's multi-issue schema: use the primary issue's confidence.
                primary = next((i for i in out["issues"] if i["issue"] == out.get("primary_issue")), None)
                conf = primary["confidence"] if primary else None
            if conf is not None:
                values.append(conf)
                labels.append(r["complaint_id"])
        fig.add_trace(go.Bar(name=label, x=labels, y=values, marker_color=CHART_SERIES[i]))
    # complaint_id ("9999970") reads as numeric to Plotly's default axis-type
    # inference, which formats it with an SI suffix ("9.99997M") -- force a
    # categorical axis so it prints as the literal ID.
    fig.update_layout(barmode="group", yaxis=dict(range=[0, 1], title="confidence"), xaxis=dict(type="category"))
    return plotly_brand_layout(fig, "Agent confidence by ticket")


def chart_tool_use_frequency(records):
    tool_labels = {
        "agent1": "Agent 1: taxonomy lookup",
        "agent2_regulation": "Agent 2: regulation index (always)",
        "agent2_crm": "Agent 2: broader CRM lookup",
        "agent3": "Agent 3: exact clause fetch",
        "agent4": "Agent 4: re-verify",
    }
    counts = {k: 0 for k in tool_labels}
    for r in records:
        a = r["agents"]
        if a["agent1"]["tool_used"]:
            counts["agent1"] += 1
        counts["agent2_regulation"] += 1  # always runs, spec Section 6
        if a["agent2"]["broader_crm_lookup_used"]:
            counts["agent2_crm"] += 1
        if a["agent3"]["tool_used"]:
            counts["agent3"] += 1
        if a["agent4"]["tool_used"]:
            counts["agent4"] += 1
    n = len(records)
    fig = go.Figure(
        go.Bar(
            y=[tool_labels[k] for k in tool_labels],
            x=[counts[k] for k in tool_labels],
            orientation="h",
            marker_color=NAVY,
            text=[f"{counts[k]}/{n}" for k in tool_labels],
            textposition="outside",
        )
    )
    fig.update_layout(xaxis=dict(range=[0, n + 0.5], dtick=1), margin=dict(l=190))
    return plotly_brand_layout(fig, "Tool-use frequency (of tickets processed)")


# ---------------------------------------------------------------------------
# Queue table -- drafts awaiting human review.
# ---------------------------------------------------------------------------
def render_queue_table(records):
    escalated = [r for r in records if r["decision"] == "ESCALATE_TO_HUMAN"]
    heading = "#### Queue: drafts awaiting human review"
    if not escalated:
        md_html(f'{heading}\n<p class="section-caption">No tickets currently awaiting human review.</p>')
        return

    rows = []
    for r in escalated:
        draft = (r["agents"]["agent3"]["output"] or {}).get("draft", "")
        draft_preview = (draft[:110] + "…") if len(draft) > 110 else draft
        reason = (r["agents"]["agent4"]["output"] or {}).get("reason", "")
        confidence = (r["agents"]["agent4"]["output"] or {}).get("confidence")
        rows.append(
            f"""
            <tr>
                <td class="mono">{r['complaint_id']}</td>
                <td>{r['company']}</td>
                <td>{r['issue']}</td>
                <td>{draft_preview}</td>
                <td>{confidence:.2f}</td>
                <td>{reason}</td>
            </tr>
            """
        )

    md_html(
        f"""
        {heading}
        <table class="queue-table">
            <thead>
                <tr>
                    <th>Complaint ID</th><th>Company</th><th>Issue</th>
                    <th>Draft (preview)</th><th>QA confidence</th><th>Escalation reason</th>
                </tr>
            </thead>
            <tbody>{''.join(rows)}</tbody>
        </table>
        """
    )


def render_auto_resolved_table(records):
    auto_resolved = [r for r in records if r["decision"] == "AUTO_RESOLVE"]
    heading = "#### Queue: auto-resolved tickets"
    if not auto_resolved:
        md_html(
            f"""
            {heading}
            <p class="section-caption">No tickets have auto-resolved in this log yet. This table renders
            correctly once a real record has decision=AUTO_RESOLVE.</p>
            """
        )
        return

    rows = []
    for r in auto_resolved:
        draft = r.get("draft") or ""
        draft_preview = (draft[:110] + "…") if len(draft) > 110 else draft
        confidence = (r["agents"]["agent4"]["output"] or {}).get("confidence")
        confidence_str = f"{confidence:.2f}" if confidence is not None else "—"
        rows.append(
            f"""
            <tr>
                <td class="mono">{r['complaint_id']}</td>
                <td>{r['company']}</td>
                <td>{r['issue']}</td>
                <td>{draft_preview}</td>
                <td>{confidence_str}</td>
            </tr>
            """
        )

    md_html(
        f"""
        {heading}
        <table class="queue-table">
            <thead>
                <tr>
                    <th>Complaint ID</th><th>Company</th><th>Issue</th>
                    <th>Draft (sent automatically)</th><th>QA confidence</th>
                </tr>
            </thead>
            <tbody>{''.join(rows)}</tbody>
        </table>
        """
    )


def render_awaiting_table(awaiting_records, decided_count):
    # Real tickets, real CRM records, zero agent decision -- kept in its own
    # section so it can never be mistaken for a decided ticket or leak into
    # a KPI. See scripts/export_dashboard_data.mjs's module docstring.
    if not awaiting_records:
        return
    rows = []
    for r in awaiting_records:
        received = (r.get("date_received") or "")[:10]
        rows.append(
            f"""
            <tr>
                <td class="mono">{r['complaint_id']}</td>
                <td>{r['company']}</td>
                <td>{r['product']}</td>
                <td>{r['issue']}</td>
                <td>{r.get('state', '')}</td>
                <td>{received}</td>
            </tr>
            """
        )
    with st.expander(f"{len(awaiting_records)} real tickets fetched live, awaiting Phase 7 (no decision yet)"):
        st.markdown(
            '<p class="section-caption">Fetched from the real CFPB API and given a real synthetic CRM '
            "record (Phase 1/2 both genuinely ran) — but no agent has looked at any of these. No "
            "severity, no draft, no escalation call. Excluded from every KPI and chart above, which are "
            f"computed only from the {decided_count} tickets that have an actual pipeline decision.</p>",
            unsafe_allow_html=True,
        )
        md_html(
            f"""
            <table class="queue-table">
                <thead>
                    <tr>
                        <th>Complaint ID</th><th>Company</th><th>Product</th>
                        <th>Issue</th><th>State</th><th>Date received</th>
                    </tr>
                </thead>
                <tbody>{''.join(rows)}</tbody>
            </table>
            """
        )


# ---------------------------------------------------------------------------
# Agent legend -- what "Agent 1/2/3/4" mean, spec Section 6. Rendered as a
# persistent reference at the top of the Technical detail tab rather than
# relying on chart hover text, which a viewer has no reason to discover on
# their own.
# ---------------------------------------------------------------------------
def render_agent_legend():
    cards = "".join(
        f"""
        <div class="agent-card">
            <div class="agent-card-num">Agent {num}</div>
            <div class="agent-card-name">{info['name']}</div>
            <div class="agent-card-tool">Tool: {info['tool']}</div>
            <div class="agent-card-when">{info['used_when']}</div>
        </div>
        """
        for num, info in AGENT_INFO.items()
    )
    md_html(f'<div class="agent-legend">{cards}</div>')


# ---------------------------------------------------------------------------
# Page
# ---------------------------------------------------------------------------
def main():
    inject_brand_css()
    log = load_pipeline_log()

    st.markdown("## Complaint Triage Orchestrator")
    st.markdown(
        '<p class="section-caption">Real CFPB complaint data + real federal regulation text + a disclosed '
        "synthetic CRM layer, triaged by four conditional-tool-use agents behind a deterministic escalation "
        "gate.</p>",
        unsafe_allow_html=True,
    )

    if log is None:
        st.warning(
            f"No pipeline data found at `{DATA_PATH}`. Run `node scripts/export_dashboard_data.mjs` "
            "from the repo root first."
        )
        render_disclosure_banner()
        return

    records = log["records"]
    awaiting_records = log.get("awaiting_records", [])

    # Category filter: single source of truth for both tabs. Read directly
    # from session_state rather than the st.multiselect(...) call itself,
    # since that widget is declared further down (inside tab_overview) but
    # this value is also needed here, before st.tabs() runs, for the
    # Technical detail tab's dynamic label -- a keyed widget's session_state
    # slot is already updated by the time the script re-runs, regardless of
    # where in the script the widget itself is declared.
    categories = []
    seen_categories = set()
    for r in records:
        p = r["product"]
        if p not in seen_categories:
            seen_categories.add(p)
            categories.append(p)
    st.session_state.setdefault("category_filter_multiselect", [])
    selected_categories = set(st.session_state.category_filter_multiselect)
    filtered_records = [r for r in records if r["product"] in selected_categories] if selected_categories else records

    technical_label = "Technical detail"
    if selected_categories:
        # Stable order matching the chart/legend/dropdown (categories'
        # own insertion order), not sorted() or set iteration order.
        technical_label = f"Technical detail ({', '.join(c for c in categories if c in selected_categories)})"

    # Seeds the queue-view toggle from a `?queue_view=...` URL query param --
    # must happen before st.segmented_control(key="queue_view") instantiates
    # below, since a keyed widget's session_state entry, once set, wins over
    # `default` on every later rerun. Only applied once per session (real
    # navigations from the bar-jump links below create a fresh session
    # anyway); a manual toggle click after that always takes priority.
    scroll_to_queue = False
    if "queue_view" not in st.session_state:
        requested_view = st.query_params.get("queue_view")
        if requested_view in ("Escalated to human", "Auto-resolved"):
            st.session_state["queue_view"] = requested_view
            scroll_to_queue = True
        else:
            # Same value segmented_control's own `default` would have used --
            # set directly instead of passing `default=` alongside a keyed
            # widget that Session State already governs, which Streamlit
            # warns is a conflicting/undefined combination.
            st.session_state["queue_view"] = "Escalated to human"

    tab_overview, tab_technical = st.tabs(["Overview", technical_label])

    with tab_overview:
        if len(records) < 50:
            st.markdown(
                f'<p class="section-caption"><strong>{len(records)} ticket(s) processed to date</strong> — '
                "this build's four agents are mock-first (spec Phase 3): only tickets with hand-verified "
                "fixture data (spec Section 6's original three, plus any added since) have a genuine "
                "pipeline decision. Real live-ticket volume arrives after Phase 7's Claude API swap; charts "
                "below reflect exactly what's real today, not a padded sample.</p>",
                unsafe_allow_html=True,
            )

        render_awaiting_table(awaiting_records, len(filtered_records))

        cols = st.columns(5)
        hs_val, hs_sub = kpi_hours_saved()
        render_kpi_card(cols[0], "Hours saved / ticket", hs_val, hs_sub)
        ca_val, ca_sub = kpi_citation_accuracy(filtered_records)
        render_kpi_card(cols[1], "Citation accuracy", ca_val, ca_sub)
        sla_val, sla_sub = kpi_sla_compliance()
        render_kpi_card(cols[2], "SLA compliance", sla_val, sla_sub)
        ea_val, ea_sub = kpi_escalation_agreement(filtered_records)
        render_kpi_card(cols[3], "Escalation agreement", ea_val, ea_sub)
        cat_val, cat_sub = kpi_category_agreement(filtered_records)
        render_kpi_card(cols[4], "Category agreement", cat_val, cat_sub)

        st.markdown("<br>", unsafe_allow_html=True)

        # Category filter (categories/selected_categories/filtered_records
        # computed earlier, before st.tabs()). Native Plotly click-to-select
        # on the donut was tried and ruled out first: 0/5 real slice clicks
        # registered a selection, and legend clicks are pure client-side
        # trace-visibility toggles that never reach Streamlit's selection
        # state at all -- worse than the bar chart's already-flaky results.
        # This multiselect is a real, guaranteed-to-register widget instead.
        #
        # Positioned above both charts, not tucked under the donut: this is
        # the primary filter (pick a category), with the escalate/auto-
        # resolve bars beside the donut as the secondary filter within it --
        # top-to-bottom placement matches that selection order.
        st.multiselect(
            "Filter by product category", options=categories, key="category_filter_multiselect",
            placeholder="All categories shown — select to filter",
        )

        left, right = st.columns(2)
        with left:
            # Deliberately built from the unfiltered `records`, with only the
            # selected slice(s) at full color and the rest dimmed -- this
            # chart IS the filter control, so it shows the whole picture with
            # the current selection highlighted, not a recomputed subset.
            st.plotly_chart(chart_category_breakdown(records, selected_categories), width='stretch')
        with right:
            # A Plotly bar-click -> table-jump interaction was tried first via
            # st.plotly_chart(..., on_select="rerun") and dropped after it
            # proved flaky under real clicks (re-verified live: sometimes a
            # click's selection state didn't land until the NEXT click,
            # sometimes it silently reset to empty -- inconsistent is worse
            # than a clean failure, and the flakiness is in Streamlit's
            # Python-JS selection bridge, not Plotly's own rendering.
            # A plain HTML <a href="?queue_view=...#queue-section"> overlay,
            # positioned over each bar with a keyed st.container for CSS
            # scoping, sidesteps that bridge entirely -- it's a real browser
            # navigation with a query param + anchor, not a Streamlit rerun
            # event. `main()` seeds st.session_state["queue_view"] from
            # st.query_params before the segmented_control below is
            # instantiated, so this and the manual toggle both drive the same
            # single source of truth.
            with st.container(key="decision_chart_wrap"):
                st.plotly_chart(chart_decision_breakdown(filtered_records), width='stretch')
                st.markdown(
                    """
                    <style>
                    .st-key-decision_chart_wrap { position: relative; }
                    /* Streamlit wraps every element (including this markdown
                       call) in its own position:relative, height:0 container
                       -- that becomes the nearest positioned ancestor and
                       steals the containing-block role before top/bottom %
                       can resolve against the wrapper above. Neutralize it. */
                    .st-key-decision_chart_wrap .stElementContainer { position: static; }
                    .st-key-decision_chart_wrap .bar-jump-link {
                        position: absolute; top: 14%; bottom: 10%;
                        border-radius: 6px; cursor: pointer;
                    }
                    .st-key-decision_chart_wrap .bar-jump-link:hover { background: rgba(21, 62, 117, 0.08); }
                    .st-key-decision_chart_wrap .bar-jump-left { left: 2%; width: 44%; }
                    .st-key-decision_chart_wrap .bar-jump-right { right: 2%; width: 44%; }
                    </style>
                    <a class="bar-jump-link bar-jump-left" title="Jump to: drafts awaiting human review"
                       href="?queue_view=Escalated+to+human#queue-section"></a>
                    <a class="bar-jump-link bar-jump-right" title="Jump to: auto-resolved tickets"
                       href="?queue_view=Auto-resolved#queue-section"></a>
                    """,
                    unsafe_allow_html=True,
                )

        st.markdown('<div id="queue-section"></div>', unsafe_allow_html=True)
        if scroll_to_queue:
            # st.markdown-injected <script> tags don't execute in Streamlit
            # (HTML is set via innerHTML, not parsed as live markup) --
            # components.v1.html runs in a real iframe, where they do. The
            # anchor in the bar-jump links' href can't do this alone: the
            # browser tries to jump to #queue-section on initial page load,
            # before Streamlit has finished rendering that element, so the
            # native jump silently misses. This polls for it instead.
            #
            # Streamlit nudges toward st.iframe as the replacement here, but
            # that only takes a `src` URL, not raw HTML/JS content -- not a
            # substitute for what this actually needs.
            components.html(
                """
                <script>
                (function () {
                    let tries = 0;
                    const tryScroll = () => {
                        const el = window.parent.document.getElementById("queue-section");
                        if (el) {
                            el.scrollIntoView({behavior: "smooth", block: "start"});
                        } else if (tries++ < 30) {
                            setTimeout(tryScroll, 100);
                        }
                    };
                    tryScroll();
                })();
                </script>
                """,
                height=0,
            )
        with st.container(key="queue_card"):
            queue_view = st.segmented_control(
                "Queue view", ["Escalated to human", "Auto-resolved"],
                key="queue_view", label_visibility="collapsed",
            )
            if queue_view == "Auto-resolved":
                render_auto_resolved_table(filtered_records)
            else:
                render_queue_table(filtered_records)

    with tab_technical:
        st.markdown(
            '<p class="section-caption">Agent-level detail, kept separate from the business-facing view '
            "(spec Section 10).</p>",
            unsafe_allow_html=True,
        )
        render_agent_legend()
        left, right = st.columns(2)
        with left:
            st.plotly_chart(chart_confidence_distribution(filtered_records), width='stretch')
        with right:
            st.plotly_chart(chart_tool_use_frequency(filtered_records), width='stretch')

        st.markdown("#### Raw pipeline log")
        st.dataframe(pd.json_normalize(filtered_records), width='stretch', height=300)

        with st.expander("Other required disclosures (spec Section 14)"):
            st.markdown(
                "- Real, live, government-verified complaints against named real companies — "
                "independent portfolio analysis, not affiliated with or endorsed by any company named in the data.\n"
                "- Escalation-agreement and similar outcome-comparison metrics are directional signals, "
                "not certified accuracy.\n"
                "- Policy citations reference real federal regulation; this is a technical demonstration, "
                "not legal advice."
            )

    render_disclosure_banner()


def render_disclosure_banner():
    st.markdown(
        '<div class="disclosure-banner">Customer/account records shown here are <strong>synthetic</strong> '
        "(spec Section 3c) — generated to demonstrate the pipeline, not real customer data. "
        "servicemember_flag and special_population_flag carry forward CFPB's own real tags field where present; "
        "everything else in the CRM record is synthetic.</div>",
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
