"""
Complaint Triage Orchestrator -- business dashboard (spec Section 10, Phase 6).

Reads dashboard/data/pipeline_log.json, generated by
scripts/export_dashboard_data.mjs from the ACTUAL committed n8n workflow --
this file computes and displays, it does not invent any pipeline logic of
its own.

Data honesty note (read before extending this file): as of this build, only
the three Section 6 fixture tickets have a genuine pipeline decision --
Phase 7's mock-to-real Claude API swap hasn't happened, so every live
ticket the Schedule/Manual trigger fetches still dead-ends. This dashboard
is built to show that real n=3 honestly (see EMPTY-STATE COPY below) rather
than pad the log with invented tickets to make charts look fuller. When a
real pilot run accumulates more records, this same code renders them --
nothing here assumes exactly 3.

Run: streamlit run dashboard/app.py
"""

import json
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go
import streamlit as st


def md_html(s: str):
    """st.markdown(unsafe_allow_html=True), but with every line's leading
    whitespace stripped first.

    Markdown treats any line indented 4+ spaces as a preformatted code
    block, independent of unsafe_allow_html -- HTML built from f-strings at
    Python nesting depth (every block in this file) trips that rule and
    renders as literal escaped tags instead of markup. textwrap.dedent()
    alone isn't enough here: it only strips the whitespace common to every
    line, but this file assembles HTML by concatenating fragments built at
    different nesting depths (e.g. table rows built inside a loop, then
    joined into a table built in the caller), so no single common prefix
    covers every line. Stripping per-line instead guarantees no line can
    trip the 4-space rule, regardless of which function contributed it.
    """
    st.markdown("\n".join(line.lstrip() for line in s.split("\n")), unsafe_allow_html=True)

# ---------------------------------------------------------------------------
# Brand palette (Leo_Chan_Brand_Identity.md, spec Section 10 -- exact values,
# not approximated).
# ---------------------------------------------------------------------------
NAVY = "#153E75"
SLATE = "#475569"
LIGHT_GREY = "#E5E7EB"
BACKGROUND = "#F8FAFC"
WHITE = "#FFFFFF"
# A small tint scale off Navy for chart series -- the brand system says
# "avoid bright colours," so chart series are navy-family, not a rainbow.
CHART_SERIES = [NAVY, "#3D6FB3", "#7FA3D1", SLATE, "#94A3B8"]

DATA_PATH = Path(__file__).resolve().parent / "data" / "pipeline_log.json"

st.set_page_config(page_title="Complaint Triage Orchestrator", layout="wide", page_icon=None)


# ---------------------------------------------------------------------------
# Styling -- none of this works out of the box in Streamlit (spec Section 10).
# ---------------------------------------------------------------------------
def inject_brand_css():
    md_html(
        f"""
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@600;700&family=Inter:wght@400;500&display=swap');

        html, body, [class*="css"] {{
            font-family: 'Inter', sans-serif;
            color: {SLATE};
            background-color: {BACKGROUND};
        }}
        h1, h2, h3, h4, .kpi-label {{
            font-family: 'Manrope', sans-serif;
            font-weight: 600;
            color: {NAVY};
        }}
        .stApp {{
            background-color: {BACKGROUND};
        }}

        /* Hide Streamlit's default chrome -- the single biggest tell an
           app wasn't designed (spec Section 10). */
        #MainMenu {{ visibility: hidden; }}
        footer {{ visibility: hidden; }}
        header {{ visibility: hidden; }}
        div[data-testid="stToolbar"] {{ visibility: hidden; }}

        /* Cap content width -- default edge-to-edge layout reads unstyled. */
        .block-container {{
            max-width: 1180px;
            padding-top: 2rem;
            padding-bottom: 6rem; /* room for the fixed disclosure banner */
        }}

        /* KPI cards: custom HTML/CSS, not st.metric (spec explicit) --
           white background, thin light-grey border, Manrope small-caps
           label, large Inter Medium navy number. */
        .kpi-card {{
            background: {WHITE};
            border: 1px solid {LIGHT_GREY};
            border-radius: 8px;
            padding: 1.1rem 1.2rem;
            height: 100%;
        }}
        .kpi-label {{
            font-size: 0.72rem;
            font-weight: 600;
            letter-spacing: 0.06em;
            text-transform: uppercase;
            color: {SLATE};
            margin-bottom: 0.5rem;
        }}
        .kpi-value {{
            font-family: 'Inter', sans-serif;
            font-weight: 500;
            font-size: 1.9rem;
            color: {NAVY};
            line-height: 1.1;
        }}
        .kpi-value.pending {{
            font-size: 1.05rem;
            font-weight: 500;
            color: {SLATE};
        }}
        .kpi-sub {{
            font-size: 0.74rem;
            color: {SLATE};
            margin-top: 0.35rem;
        }}

        /* Persistent, non-dismissible synthetic-CRM disclosure banner. */
        .disclosure-banner {{
            position: fixed;
            bottom: 0;
            left: 0;
            right: 0;
            background: {SLATE};
            color: {WHITE};
            font-size: 0.8rem;
            padding: 0.65rem 1.5rem;
            z-index: 999;
            text-align: center;
        }}

        .queue-table {{
            width: 100%;
            border-collapse: collapse;
            font-size: 0.86rem;
        }}
        .queue-table th {{
            text-align: left;
            font-family: 'Manrope', sans-serif;
            font-weight: 600;
            font-size: 0.72rem;
            text-transform: uppercase;
            letter-spacing: 0.04em;
            color: {SLATE};
            border-bottom: 1px solid {LIGHT_GREY};
            padding: 0.5rem 0.6rem;
        }}
        .queue-table td {{
            border-bottom: 1px solid {LIGHT_GREY};
            padding: 0.6rem 0.6rem;
            vertical-align: top;
            color: {SLATE};
        }}
        .queue-table td.mono {{
            font-family: monospace;
            color: {NAVY};
        }}
        .section-caption {{
            font-size: 0.82rem;
            color: {SLATE};
            margin-top: -0.5rem;
            margin-bottom: 1rem;
        }}
        </style>
        """
    )


def plotly_brand_layout(fig: go.Figure, title: str) -> go.Figure:
    fig.update_layout(
        title=dict(text=title, font=dict(family="Manrope, sans-serif", size=14, color=NAVY)),
        font=dict(family="Inter, sans-serif", size=12, color=SLATE),
        plot_bgcolor=WHITE,
        paper_bgcolor=WHITE,
        margin=dict(l=10, r=10, t=40, b=10),
        legend=dict(font=dict(family="Inter, sans-serif", size=11)),
    )
    fig.update_xaxes(showline=True, linecolor=LIGHT_GREY, gridcolor=LIGHT_GREY)
    fig.update_yaxes(showline=True, linecolor=LIGHT_GREY, gridcolor=LIGHT_GREY)
    return fig


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
@st.cache_data
def load_pipeline_log():
    if not DATA_PATH.exists():
        return None
    with open(DATA_PATH, encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# KPI computation (spec Section 9's five metrics). Each function documents
# WHY it either returns a real number from the log or an honest "not yet
# measurable" state -- no metric here is invented to fill a card.
# ---------------------------------------------------------------------------
def kpi_hours_saved():
    # Spec Section 9: "only the pipeline's own processing time still awaits
    # a real measurement at Phase 7" -- this build has never run against a
    # real, timed production schedule, only a manually-invoked test
    # harness. Reporting a number here would be fabricating exactly the
    # kind of figure this project has spent five phases refusing to fake.
    return None, "real pipeline timing (manual baseline: ~10 min/ticket, sourced)"


def kpi_sla_compliance():
    # Same reasoning as hours saved: "draft ready inside the 15-day window"
    # requires a real elapsed-time measurement from an actual production
    # run, which doesn't exist yet -- only manual test-harness executions.
    return None, "real pipeline timing measurement"


def kpi_citation_accuracy(records):
    # Real, computed: for every ticket where Agent 3 cited a regulation,
    # did the exact-clause-fetch tool actually resolve it against the
    # cached, real regulation corpus? This is QA-verified, not
    # self-reported -- Agent 3's and Agent 4's tool_result.found both come
    # from independent real lookups (see README's regulation-search
    # limitation note for the ceiling this implies).
    cited = [r for r in records if r["agents"]["agent3"]["tool_used"]]
    if not cited:
        return None, "No drafts cited a regulation yet"
    correct = sum(1 for r in cited if (r["agents"]["agent3"]["tool_result"] or {}).get("found"))
    pct = round(100 * correct / len(cited))
    return pct, f"{correct}/{len(cited)} cited drafts, QA-verified against real regulation text"


def kpi_escalation_agreement(records):
    # Real, computed -- and expected to read low here. See README/spec
    # Section 8: CFPB's own outcome category is a coarse administrative
    # label, not a severity judgment, so low agreement on this fixture set
    # is a demonstration of the metric's own honest limits, not a pipeline
    # defect. Never report this as accuracy.
    with_gt = [r for r in records if r.get("ground_truth")]
    if not with_gt:
        return None, "No ground-truth comparisons yet"
    agree = sum(1 for r in with_gt if r["ground_truth"]["agrees_with_ground_truth"])
    pct = round(100 * agree / len(with_gt))
    return pct, f"{agree}/{len(with_gt)} agree with CFPB's outcome fields — directional signal, not accuracy (Section 8)"


def kpi_category_agreement(records):
    # Real, computed: does Agent 1's classified issue match what the
    # consumer actually filed with CFPB, at either the issue or sub-issue
    # level (Ticket C's classification lands at the sub-issue level, since
    # that's the substantive category for that compound ticket -- see
    # spec Section 6).
    if not records:
        return None, "No classifications yet"
    matches = 0
    for r in records:
        out = r["agents"]["agent1"]["output"] or {}
        classified = out.get("primary_issue") or out.get("issue")
        if classified and classified in (r.get("issue"), r.get("sub_issue")):
            matches += 1
    pct = round(100 * matches / len(records))
    return pct, f"{matches}/{len(records)} match CFPB's own filed product/issue category"


def render_kpi_card(col, label, value, sub):
    with col:
        if value is None:
            value_html = '<div class="kpi-value pending">Awaiting Phase 7</div>'
            sub_html = f'<div class="kpi-sub">{sub}</div>'
        else:
            value_html = f'<div class="kpi-value">{value}%</div>'
            sub_html = f'<div class="kpi-sub">{sub}</div>'
        md_html(
            f"""
            <div class="kpi-card">
                <div class="kpi-label">{label}</div>
                {value_html}
                {sub_html}
            </div>
            """
        )


# ---------------------------------------------------------------------------
# Charts
# ---------------------------------------------------------------------------
def chart_decision_breakdown(records):
    counts = {"Escalated to human": 0, "Auto-resolved": 0}
    for r in records:
        if r["decision"] == "ESCALATE_TO_HUMAN":
            counts["Escalated to human"] += 1
        else:
            counts["Auto-resolved"] += 1
    fig = go.Figure(
        go.Bar(
            x=list(counts.keys()),
            y=list(counts.values()),
            marker_color=[NAVY, "#94A3B8"],
            text=list(counts.values()),
            textposition="outside",
            width=0.5,
        )
    )
    fig.update_layout(yaxis=dict(dtick=1))
    return plotly_brand_layout(fig, "Escalate vs. auto-resolve")


def chart_category_breakdown(records):
    counts = {}
    for r in records:
        counts[r["product"]] = counts.get(r["product"], 0) + 1
    fig = go.Figure(
        go.Pie(
            labels=list(counts.keys()),
            values=list(counts.values()),
            marker=dict(colors=CHART_SERIES),
            hole=0.55,
            textfont=dict(family="Inter, sans-serif"),
        )
    )
    return plotly_brand_layout(fig, "Product category breakdown")


def chart_confidence_distribution(records):
    fig = go.Figure()
    for i, agent_key in enumerate(["agent1", "agent4"]):
        label = "Agent 1 (Classification)" if agent_key == "agent1" else "Agent 4 (QA/scoring)"
        values, labels = [], []
        for r in records:
            out = r["agents"][agent_key]["output"] or {}
            conf = out.get("confidence")
            if conf is None and "issues" in out:
                # Ticket C's multi-issue schema: use the primary issue's confidence.
                primary = next((i for i in out["issues"] if i["issue"] == out.get("primary_issue")), None)
                conf = primary["confidence"] if primary else None
            if conf is not None:
                values.append(conf)
                labels.append(r["complaint_id"])
        fig.add_trace(go.Bar(name=label, x=labels, y=values, marker_color=CHART_SERIES[i]))
    # complaint_id ("9999970") reads as numeric to Plotly's default axis-type
    # inference, which formats it with an SI suffix ("9.99997M") -- force a
    # categorical axis so it prints as the literal ID.
    fig.update_layout(barmode="group", yaxis=dict(range=[0, 1], title="confidence"), xaxis=dict(type="category"))
    return plotly_brand_layout(fig, "Agent confidence by ticket")


def chart_tool_use_frequency(records):
    tool_labels = {
        "agent1": "Agent 1: taxonomy lookup",
        "agent2_regulation": "Agent 2: regulation index (always)",
        "agent2_crm": "Agent 2: broader CRM lookup",
        "agent3": "Agent 3: exact clause fetch",
        "agent4": "Agent 4: re-verify",
    }
    counts = {k: 0 for k in tool_labels}
    for r in records:
        a = r["agents"]
        if a["agent1"]["tool_used"]:
            counts["agent1"] += 1
        counts["agent2_regulation"] += 1  # always runs, spec Section 6
        if a["agent2"]["broader_crm_lookup_used"]:
            counts["agent2_crm"] += 1
        if a["agent3"]["tool_used"]:
            counts["agent3"] += 1
        if a["agent4"]["tool_used"]:
            counts["agent4"] += 1
    n = len(records)
    fig = go.Figure(
        go.Bar(
            y=[tool_labels[k] for k in tool_labels],
            x=[counts[k] for k in tool_labels],
            orientation="h",
            marker_color=NAVY,
            text=[f"{counts[k]}/{n}" for k in tool_labels],
            textposition="outside",
        )
    )
    fig.update_layout(xaxis=dict(range=[0, n + 0.5], dtick=1), margin=dict(l=190))
    return plotly_brand_layout(fig, "Tool-use frequency (of tickets processed)")


# ---------------------------------------------------------------------------
# Queue table -- drafts awaiting human review.
# ---------------------------------------------------------------------------
def render_queue_table(records):
    escalated = [r for r in records if r["decision"] == "ESCALATE_TO_HUMAN"]
    if not escalated:
        st.markdown('<p class="section-caption">No tickets currently awaiting human review.</p>', unsafe_allow_html=True)
        return

    rows = []
    for r in escalated:
        draft = (r["agents"]["agent3"]["output"] or {}).get("draft", "")
        draft_preview = (draft[:110] + "…") if len(draft) > 110 else draft
        reason = (r["agents"]["agent4"]["output"] or {}).get("reason", "")
        confidence = (r["agents"]["agent4"]["output"] or {}).get("confidence")
        rows.append(
            f"""
            <tr>
                <td class="mono">{r['complaint_id']}</td>
                <td>{r['company']}</td>
                <td>{r['issue']}</td>
                <td>{draft_preview}</td>
                <td>{confidence:.2f}</td>
                <td>{reason}</td>
            </tr>
            """
        )

    md_html(
        f"""
        <table class="queue-table">
            <thead>
                <tr>
                    <th>Complaint ID</th><th>Company</th><th>Issue</th>
                    <th>Draft (preview)</th><th>QA confidence</th><th>Escalation reason</th>
                </tr>
            </thead>
            <tbody>{''.join(rows)}</tbody>
        </table>
        """
    )


# ---------------------------------------------------------------------------
# Page
# ---------------------------------------------------------------------------
def main():
    inject_brand_css()
    log = load_pipeline_log()

    st.markdown("## Complaint Triage Orchestrator")
    st.markdown(
        '<p class="section-caption">Real CFPB complaint data + real federal regulation text + a disclosed '
        "synthetic CRM layer, triaged by four conditional-tool-use agents behind a deterministic escalation "
        "gate.</p>",
        unsafe_allow_html=True,
    )

    if log is None:
        st.warning(
            f"No pipeline data found at `{DATA_PATH}`. Run `node scripts/export_dashboard_data.mjs` "
            "from the repo root first."
        )
        render_disclosure_banner()
        return

    records = log["records"]

    tab_overview, tab_technical = st.tabs(["Overview", "Technical detail"])

    with tab_overview:
        if len(records) < 10:
            st.markdown(
                f'<p class="section-caption"><strong>{len(records)} ticket(s) processed to date</strong> — '
                "this build's four agents are mock-first (spec Phase 3): only the three Section 6 fixture "
                "tickets have a genuine pipeline decision. Real live-ticket volume arrives after Phase 7's "
                "Claude API swap; charts below reflect exactly what's real today, not a padded sample.</p>",
                unsafe_allow_html=True,
            )

        cols = st.columns(5)
        hs_val, hs_sub = kpi_hours_saved()
        render_kpi_card(cols[0], "Hours saved / ticket", hs_val, hs_sub)
        ca_val, ca_sub = kpi_citation_accuracy(records)
        render_kpi_card(cols[1], "Citation accuracy", ca_val, ca_sub)
        sla_val, sla_sub = kpi_sla_compliance()
        render_kpi_card(cols[2], "SLA compliance", sla_val, sla_sub)
        ea_val, ea_sub = kpi_escalation_agreement(records)
        render_kpi_card(cols[3], "Escalation agreement", ea_val, ea_sub)
        cat_val, cat_sub = kpi_category_agreement(records)
        render_kpi_card(cols[4], "Category agreement", cat_val, cat_sub)

        st.markdown("<br>", unsafe_allow_html=True)
        left, right = st.columns(2)
        with left:
            st.plotly_chart(chart_decision_breakdown(records), use_container_width=True)
        with right:
            st.plotly_chart(chart_category_breakdown(records), use_container_width=True)

        st.markdown("#### Queue: drafts awaiting human review")
        render_queue_table(records)

    with tab_technical:
        st.markdown(
            '<p class="section-caption">Agent-level detail, kept separate from the business-facing view '
            "(spec Section 10).</p>",
            unsafe_allow_html=True,
        )
        left, right = st.columns(2)
        with left:
            st.plotly_chart(chart_confidence_distribution(records), use_container_width=True)
        with right:
            st.plotly_chart(chart_tool_use_frequency(records), use_container_width=True)

        st.markdown("#### Raw pipeline log")
        st.dataframe(pd.json_normalize(records), use_container_width=True, height=300)

        with st.expander("Other required disclosures (spec Section 14)"):
            st.markdown(
                "- Real, live, government-verified complaints against named real companies — "
                "independent portfolio analysis, not affiliated with or endorsed by any company named in the data.\n"
                "- Escalation-agreement and similar outcome-comparison metrics are directional signals, "
                "not certified accuracy.\n"
                "- Policy citations reference real federal regulation; this is a technical demonstration, "
                "not legal advice."
            )

    render_disclosure_banner()


def render_disclosure_banner():
    st.markdown(
        '<div class="disclosure-banner">Customer/account records shown here are <strong>synthetic</strong> '
        "(spec Section 3c) — generated to demonstrate the pipeline, not real customer data. "
        "servicemember_flag and special_population_flag carry forward CFPB's own real tags field where present; "
        "everything else in the CRM record is synthetic.</div>",
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
