"""
Complaint Triage Orchestrator -- business dashboard (spec Section 10, Phase 6).

Reads dashboard/data/pipeline_log.json, generated by
scripts/export_dashboard_data.mjs from the ACTUAL committed n8n workflow --
this file computes and displays, it does not invent any pipeline logic of
its own.

Data honesty note (read before extending this file): as of this build, every
record here has a genuine pipeline decision -- the hand-verified fixtures
(spec Section 6) via real Agent 1-4 or the mock decision layer, and (since
Phase 7's mock-to-real Claude API swap shipped) any further live ticket the
Schedule/Manual trigger fetches, via the real Product path. There's no more
"fetched but undecided" state to honestly represent, so this dashboard just
shows real, small n (see EMPTY-STATE COPY below) rather than pad the log
with invented tickets to make charts look fuller. When a real pilot run
accumulates more records, this same code renders them -- nothing here
assumes an exact count.

Run: streamlit run dashboard/app.py
"""

import json
from pathlib import Path
from urllib.parse import quote

import pandas as pd
import plotly.graph_objects as go
import streamlit as st
import streamlit.components.v1 as components

from sheets_source import fetch_live_pipeline_log


def md_html(s: str):
    """st.markdown(unsafe_allow_html=True), but with every line's leading
    whitespace stripped first.

    Markdown treats any line indented 4+ spaces as a preformatted code
    block, independent of unsafe_allow_html -- HTML built from f-strings at
    Python nesting depth (every block in this file) trips that rule and
    renders as literal escaped tags instead of markup. textwrap.dedent()
    alone isn't enough here: it only strips the whitespace common to every
    line, but this file assembles HTML by concatenating fragments built at
    different nesting depths (e.g. table rows built inside a loop, then
    joined into a table built in the caller), so no single common prefix
    covers every line. Stripping per-line instead guarantees no line can
    trip the 4-space rule, regardless of which function contributed it.
    """
    st.markdown("\n".join(line.lstrip() for line in s.split("\n")), unsafe_allow_html=True)

# ---------------------------------------------------------------------------
# Brand palette (Leo_Chan_Brand_Identity.md, spec Section 10 -- exact values,
# not approximated).
# ---------------------------------------------------------------------------
NAVY = "#153E75"
SLATE = "#475569"
LIGHT_GREY = "#E5E7EB"
BACKGROUND = "#F8FAFC"
WHITE = "#FFFFFF"
# A small tint scale off Navy for chart series -- the brand system says
# "avoid bright colours," so chart series are navy-family, not a rainbow.
CHART_SERIES = [NAVY, "#3D6FB3", "#7FA3D1", SLATE, "#94A3B8"]

# Agent roles (spec Section 6) -- referenced both in chart labels (so a bar
# or bar-group is self-explanatory without hovering) and in the persistent
# legend rendered at the top of the Technical detail tab (so it doesn't
# depend on a viewer noticing the chart labels at all).
AGENT_INFO = {
    1: {"name": "Classification", "tool": "Regulatory taxonomy lookup", "used_when": "Only when the narrative is ambiguous relative to the filed category"},
    2: {"name": "Research", "tool": "Synthetic CRM lookup + regulation-text lookup", "used_when": "Regulation lookup always; special-population check always; broader CRM context only when relevant"},
    3: {"name": "Drafting", "tool": "Exact regulation clause fetch", "used_when": "Only when citing a specific provision"},
    4: {"name": "QA / escalation-scoring", "tool": "Re-verify a cited clause or CRM fact", "used_when": "Only when the draft makes a checkable claim"},
}

DATA_PATH = Path(__file__).resolve().parent / "data" / "pipeline_log.json"

st.set_page_config(page_title="Complaint Triage Orchestrator", layout="wide", page_icon=None)


# ---------------------------------------------------------------------------
# Styling -- none of this works out of the box in Streamlit (spec Section 10).
# ---------------------------------------------------------------------------
def inject_brand_css():
    md_html(
        f"""
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@600;700&family=Inter:wght@400;500&display=swap');

        html, body, [class*="css"] {{
            font-family: 'Inter', sans-serif;
            color: {SLATE};
            background-color: {BACKGROUND};
        }}
        h1, h2, h3, h4, .kpi-label {{
            font-family: 'Manrope', sans-serif;
            font-weight: 600;
            color: {NAVY};
        }}
        .stApp {{
            background-color: {BACKGROUND};
        }}

        /* Hide Streamlit's default chrome -- the single biggest tell an
           app wasn't designed (spec Section 10). */
        #MainMenu {{ visibility: hidden; }}
        footer {{ visibility: hidden; }}
        header {{ visibility: hidden; }}
        div[data-testid="stToolbar"] {{ visibility: hidden; }}

        /* Cap content width -- default edge-to-edge layout reads unstyled. */
        .block-container {{
            max-width: 1180px;
            padding-top: 2rem;
            padding-bottom: 2rem;
        }}

        /* KPI cards: custom HTML/CSS, not st.metric (spec explicit) --
           white background, thin light-grey border, Manrope small-caps
           label, large Inter Medium navy number. */
        .kpi-card {{
            background: {WHITE};
            border: 1px solid {LIGHT_GREY};
            border-radius: 8px;
            padding: 1.1rem 1.2rem;
            height: 100%;
            /* `height: 100%` alone doesn't equalize these across the row --
               Streamlit's own internal wrappers between st.columns()'s flex
               row and this card (an unnamed centering div with
               align-items: center among them) don't propagate height:100%
               down the chain, so each card still shrinks to its own content
               (verified live: 126px-197px across the 5 cards depending on
               sub-label length). A min-height sized to the longest current
               sub-label (Missed-risk rate's multi-line text) is a simpler,
               more robust fix than fighting undocumented internal DOM. */
            min-height: 200px;
        }}
        .kpi-label {{
            font-size: 0.72rem;
            font-weight: 600;
            letter-spacing: 0.06em;
            text-transform: uppercase;
            color: {SLATE};
            margin-bottom: 0.5rem;
        }}
        .kpi-value {{
            font-family: 'Inter', sans-serif;
            font-weight: 500;
            font-size: 1.9rem;
            color: {NAVY};
            line-height: 1.1;
        }}
        .kpi-value.pending {{
            font-size: 1.05rem;
            font-weight: 500;
            color: {SLATE};
        }}
        .kpi-sub {{
            font-size: 0.74rem;
            color: {SLATE};
            margin-top: 0.35rem;
        }}

        /* Persistent (always rendered, no dismiss control), but NOT pinned
           to the viewport -- a fixed-position banner stayed visible while
           scrolling in a way that read as demanding attention rather than
           just disclosing. A normal block at the end of the page content
           is still persistent in the sense the spec means (can't be
           dismissed, always present), just not glued to the screen. */
        .disclosure-banner {{
            background: {SLATE};
            color: {WHITE};
            font-size: 0.8rem;
            padding: 0.65rem 1.5rem;
            border-radius: 6px;
            text-align: center;
            margin-top: 2rem;
        }}

        .queue-table {{
            width: 100%;
            border-collapse: collapse;
            font-size: 0.86rem;
        }}
        .queue-table th {{
            text-align: left;
            font-family: 'Manrope', sans-serif;
            font-weight: 600;
            font-size: 0.72rem;
            text-transform: uppercase;
            letter-spacing: 0.04em;
            color: {SLATE};
            border-bottom: 1px solid {LIGHT_GREY};
            padding: 0.5rem 0.6rem;
        }}
        .queue-table td {{
            border-bottom: 1px solid {LIGHT_GREY};
            padding: 0.6rem 0.6rem;
            vertical-align: top;
            color: {SLATE};
        }}
        .queue-table td.mono {{
            font-family: monospace;
            color: {NAVY};
        }}
        /* Per-ticket retrieval indicator in the queue tables (Phase 9
           revision -- see retrieval_badge_html's docstring for why this no
           longer reports lexical-vs-semantic agreement). Kept inside the
           existing navy/slate palette rather than introducing new accent
           colors -- "flagged" gets a filled pill (same treatment as the
           disclosure banner) since it's the state worth a reviewer's eye,
           every other state stays plain text. */
        .retrieval-pre-rag {{
            color: {SLATE};
            font-style: italic;
        }}
        .retrieval-lexical {{
            color: {SLATE};
        }}
        .retrieval-grounded {{
            color: {NAVY};
            font-weight: 500;
        }}
        .retrieval-none-applicable {{
            color: {SLATE};
        }}
        .retrieval-flagged-badge {{
            display: inline-block;
            background: {SLATE};
            color: {WHITE};
            font-size: 0.72rem;
            font-weight: 600;
            padding: 0.15rem 0.5rem;
            border-radius: 4px;
        }}
        .retrieval-detail {{
            font-size: 0.76rem;
            color: {SLATE};
            margin-top: 0.3rem;
        }}
        /* Draft preview cell is a real link (a plain browser navigation with
           a query param, same mechanism as the bar-jump links below -- see
           main()'s handling of ?view_draft=...) that opens the full draft in
           a popup. Styled to read as clickable without looking like a
           generic blue hyperlink. */
        /* !important: Streamlit's own markdown renderer applies a default
           link color/underline to every <a> with higher effective priority
           than a plain class rule here (confirmed live -- without this the
           link rendered in Streamlit's default blue regardless). */
        a.draft-preview-link {{
            color: inherit !important;
            text-decoration: none !important;
            cursor: pointer;
        }}
        a.draft-preview-link:hover {{
            color: {NAVY} !important;
            text-decoration: underline !important;
        }}
        .section-caption {{
            font-size: 0.82rem;
            color: {SLATE};
            margin-top: -0.5rem;
            margin-bottom: 1rem;
        }}

        /* Agent legend -- persistent reference for what "Agent 1/2/3/4" mean. */
        .agent-legend {{
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 0.75rem;
            margin-bottom: 1.5rem;
        }}
        .agent-card {{
            background: {WHITE};
            border: 1px solid {LIGHT_GREY};
            border-left: 3px solid {NAVY};
            border-radius: 6px;
            padding: 0.75rem 0.9rem;
        }}
        .agent-card-num {{
            font-family: 'Manrope', sans-serif;
            font-weight: 600;
            font-size: 0.72rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
            color: {SLATE};
        }}
        .agent-card-name {{
            font-family: 'Manrope', sans-serif;
            font-weight: 700;
            font-size: 1rem;
            color: {NAVY};
            margin: 0.15rem 0 0.4rem 0;
        }}
        .agent-card-tool {{
            font-size: 0.78rem;
            color: {SLATE};
            margin-bottom: 0.3rem;
        }}
        .agent-card-when {{
            font-size: 0.74rem;
            color: {SLATE};
            font-style: italic;
        }}

        /* A multiselect with every option already picked (e.g. the category
           filter with both categories selected) pops open to an empty "No
           results" list on click -- there's genuinely nothing left to add,
           so the message just reads as clutter. Hide it globally; no
           dropdown in this dashboard needs it. */
        [data-testid="stSelectboxVirtualDropdownEmpty"] {{ display: none !important; }}

        /* Queue card: the segmented control re-skinned as tabs attached
           directly to its table, not a separate widget floating above it
           (spec-adjacent UX fix -- Streamlit's default segmented_control is
           a standalone pill-button group with no way to visually attach it
           to what it controls). One bordered white card holds the tab
           strip and the table; the active tab's white background matches
           the card body below it so it reads as "open," while the inactive
           tab sits on the strip's grey background and looks receded. */
        .st-key-queue_card {{
            background: {WHITE};
            border: 1px solid {LIGHT_GREY};
            border-radius: 8px;
            overflow: hidden;
        }}
        .st-key-queue_card .stElementContainer {{ margin-bottom: 0 !important; }}
        /* The segmented_control's own element-container ships with an
           inline shrink-to-fit width (its content's natural size, e.g.
           ~220px) rather than stretching to the card -- override so the
           tab strip actually spans full width instead of sitting stranded
           in the top-left corner. */
        .st-key-queue_card .st-key-queue_view {{ width: 100% !important; }}
        .st-key-queue_card [data-testid="stButtonGroup"] {{
            display: flex;
            width: 100%;
            background: {BACKGROUND};
            border-bottom: 1px solid {LIGHT_GREY};
        }}
        /* Both buttons actually share ONE wrapper div (not one each) as the
           real flex child of stButtonGroup -- and that wrapper ships with
           Streamlit's own `max-width: fit-content`, which caps it at its
           content's natural size and defeats flex-grow before it can do
           anything. Override the cap, then let the buttons (real flex
           items of THIS wrapper) split its width evenly. */
        .st-key-queue_card [data-testid="stButtonGroup"] > div {{
            flex: 1 1 0;
            max-width: none !important;
            width: 100%;
        }}
        .st-key-queue_card [data-testid^="stBaseButton-segmented_control"] {{
            flex: 1 1 0;
            min-width: 0;
            border: none !important;
            border-radius: 0 !important;
            background: transparent !important;
            box-shadow: none !important;
            color: {SLATE} !important;
            font-family: 'Manrope', sans-serif !important;
            font-weight: 600 !important;
            font-size: 0.85rem !important;
            padding: 0.75rem 0.4rem !important;
            margin: 0 !important;
            white-space: normal !important;
            overflow: visible !important;
            text-overflow: clip !important;
        }}
        /* Exact (not prefix) match -- only the inactive-tab testid, so this
           doesn't fight the active tab's own white background on hover.
           The click already registers across the button's full box (it's a
           real <button> spanning the whole tab cell, verified live), but
           without this there was no visual feedback confirming that away
           from the centered text, which reads as "only the label is
           clickable" even though the whole area always was. */
        .st-key-queue_card [data-testid="stBaseButton-segmented_control"]:hover {{
            background: rgba(21, 62, 117, 0.06) !important;
            color: {NAVY} !important;
        }}
        .st-key-queue_card [data-testid^="stBaseButton-segmented_control"] * {{
            white-space: normal !important;
            overflow: visible !important;
            text-overflow: clip !important;
            text-align: center !important;
        }}
        .st-key-queue_card [data-testid="stBaseButton-segmented_controlActive"] {{
            background: {WHITE} !important;
            color: {NAVY} !important;
            box-shadow: inset 0 -3px 0 0 {NAVY} !important;
        }}
        .st-key-queue_card .stElementContainer:not(:has([data-testid="stButtonGroup"])) {{
            padding: 0.9rem 1.25rem 1.25rem;
        }}
        .st-key-queue_card .queue-table {{ margin: 0; }}
        .st-key-queue_card h4:first-child {{ margin-top: 0; }}
        </style>
        """
    )


def plotly_brand_layout(fig: go.Figure, title: str) -> go.Figure:
    fig.update_layout(
        title=dict(text=title, font=dict(family="Manrope, sans-serif", size=14, color=NAVY)),
        font=dict(family="Inter, sans-serif", size=12, color=SLATE),
        plot_bgcolor=WHITE,
        paper_bgcolor=WHITE,
        margin=dict(l=10, r=10, t=40, b=10),
        legend=dict(font=dict(family="Inter, sans-serif", size=11)),
    )
    fig.update_xaxes(showline=True, linecolor=LIGHT_GREY, gridcolor=LIGHT_GREY)
    fig.update_yaxes(showline=True, linecolor=LIGHT_GREY, gridcolor=LIGHT_GREY)
    return fig


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------
@st.cache_data(ttl=300)
def load_pipeline_log():
    """Live Sheet first (re-polled every 5 min via the ttl above, so a
    freshly-processed ticket shows up without restarting the app), falling
    back to the committed static snapshot when no service-account secret is
    configured or the live call fails -- see sheets_source.py."""
    live = fetch_live_pipeline_log()
    if live is not None:
        return live
    if not DATA_PATH.exists():
        return None
    with open(DATA_PATH, encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# KPI computation (spec Section 9's five metrics). Each function documents
# WHY it either returns a real number from the log or an honest "not yet
# measurable" state -- no metric here is invented to fill a card.
# ---------------------------------------------------------------------------
def kpi_hours_saved():
    # Spec Section 9: measured pipeline time vs. the locked manual baseline
    # (~10 min/ticket). First real measurement, n=1: complaint 24332933,
    # trigger-fired 2026-08-17, real n8n execution #240 (13.678s: watermark
    # fetch through all 4 real Claude agent calls, ending at a Google
    # Sheets credential failure) + #241 (3.151s retry, resuming from the
    # failed node -- no agents re-run, no added API cost -- to complete the
    # write) = 16.829s real end-to-end pipeline time for one ticket.
    manual_baseline_seconds = 10 * 60
    measured_seconds = 16.829
    pct_faster = round(100 * (manual_baseline_seconds - measured_seconds) / manual_baseline_seconds)
    minutes_saved = round((manual_baseline_seconds - measured_seconds) / 60, 1)
    return pct_faster, f"{minutes_saved} min saved/ticket vs. ~10 min manual baseline (n=1, real timed run)"


def kpi_sla_compliance():
    # Spec Section 9: % of complaints with a compliant draft ready inside
    # the 15-day CFPB window. Same n=1 measurement as hours saved --
    # 16.829s is trivially inside a 15-day window, so this ticket is
    # compliant; a single real data point, not yet a meaningful rate.
    return 100, "1/1 tickets with a compliant draft ready inside the 15-day CFPB window (n=1, real timed run)"


def kpi_citation_accuracy(records):
    # Real, computed: for every ticket where Agent 3 cited a regulation,
    # did the exact-clause-fetch tool actually resolve it against the
    # cached, real regulation corpus? This is QA-verified, not
    # self-reported -- Agent 3's and Agent 4's tool_result.found both come
    # from independent real lookups (see README's regulation-search
    # limitation note for the ceiling this implies).
    cited = [r for r in records if r["agents"]["agent3"]["tool_used"]]
    if not cited:
        return None, "No drafts cited a regulation yet"
    correct = sum(1 for r in cited if (r["agents"]["agent3"]["tool_result"] or {}).get("found"))
    pct = round(100 * correct / len(cited))
    return pct, f"{correct}/{len(cited)} cited drafts, QA-verified against real regulation text"


def build_retrieval_grounding_footnote_html(records):
    """Retrieval-grounding footnote (Phase 9 revision of the Phase 8
    dual-signal footnote).

    Phase 8 built this footnote when retrieval ran *after* Agent 2 as a
    pure post-hoc audit trail -- neither tool's result fed back into any
    agent's prompt, so "did lexical and semantic agree" was the only
    honest thing to report. Phase 9 moved retrieval *before* Agent 2 and
    made its output the thing Agent 2 grounds a citation in (or explicitly
    declines to cite against) -- lexical/semantic agreement stopped being
    the interesting question the day retrieval started shaping the
    decision instead of just watching it. Reporting an "agree/disagree"
    rate here after that change reads as an ongoing comparison between two
    interchangeable tools, which misrepresents what's actually being
    checked now: whether Agent 2's citation is grounded in what retrieval
    (either tool) surfaced, not whether the two tools' top picks match.

    Also scoped to real (non-fixture) tickets only, and says so -- the 12
    earlier tickets in this pilot were decided under Phase 7 (real Agent
    1-4, before any retrieval architecture existed) and never ran either
    search, so folding them into this count would silently compare tickets
    that never had retrieval to ones that did.

    Deliberately plain-language and free of per-ticket detail: an earlier
    version named every flagged ticket with an identical repeated sentence
    (just the ID changed) and used internal vocabulary ("Product-path",
    "retrieval actually surfaced") that assumes pipeline knowledge this
    dashboard's actual reader -- a business/compliance reviewer, not a
    pipeline engineer -- doesn't have and doesn't need. The per-ticket
    detail already lives one scroll down, as the Retrieval column's
    "Flagged" badge on each row (see retrieval_badge_html) -- repeating it
    here in prose was pure duplication. This footnote's only job is the
    one number a reviewer actually needs: how many of this system's own
    citations have been confirmed against the reference library so far.
    Pure string-building, no Streamlit calls, so it's testable without
    running the app.
    """
    grounded_pool = [r for r in records if r["agents"]["agent2"].get("semantic_top_citation")]
    if not grounded_pool:
        return (
            '<p class="section-caption"><strong>Regulation-citation verification:</strong> no real tickets in '
            "this data source yet — this check only runs on live tickets, not the hand-verified test cases. "
            "See eval/kpi_results.json for a direct, offline comparison of the two retrieval tools against 18 "
            "hand-verified held-out tickets (semantic recall 90% vs. lexical 50%).</p>"
        )

    flagged = [
        r for r in grounded_pool
        if r["agents"]["agent2"].get("outside_cached_corpus") or r["agents"]["agent2"].get("citation_not_in_retrieval")
    ]
    flagged_ids = {r["complaint_id"] for r in flagged}
    grounded = [
        r for r in grounded_pool
        if r["agents"]["agent2"]["output"].get("citation") and r["complaint_id"] not in flagged_ids
    ]
    declined = [r for r in grounded_pool if not r["agents"]["agent2"]["output"].get("citation")]

    # Leads with what the check DOES (a safety property: nothing unverified
    # ships silently) rather than a bare "X confirmed" count -- a low or
    # zero confirmed-count reads as "the system doesn't work" if it's the
    # first number a reader sees, when the actual story at this pilot's
    # current size is closer to the opposite: every flagged citation named
    # a real, correctly-identified regulation that simply isn't in this
    # pilot's still-small reference library yet, and every one of them was
    # caught and routed for review rather than shipped unverified -- a
    # coverage gap, not a correctness failure. Omits the "N confirmed"
    # clause entirely when zero, rather than leading with a number that
    # would otherwise need a defensive caveat right next to it.
    parts = [
        '<p class="section-caption"><strong>Regulation-citation verification:</strong> this check flags any '
        "citation that doesn't match this pilot's reference library, so it's never sent out unverified."
    ]
    if grounded:
        parts.append(f" {len(grounded)} of {len(grounded_pool)} real citation(s) matched the library and are confirmed.")
    if flagged:
        parts.append(
            f" {len(flagged)} cited a real regulation outside this still-small library's current coverage, and "
            "were automatically routed for human review instead of shipping unverified — see the Flagged rows below."
        )
    if declined:
        parts.append(f" {len(declined)} ticket(s) had no applicable regulation to cite at all.")
    parts.append("</p>")
    return "".join(parts)


def render_retrieval_grounding_footnote(records):
    md_html(build_retrieval_grounding_footnote_html(records))


def retrieval_badge_html(record):
    """Per-ticket retrieval indicator for the queue tables (Phase 9
    revision -- see build_retrieval_grounding_footnote_html's docstring for
    why the headline signal is grounding, not lexical-vs-semantic
    agreement). Pure string building, no Streamlit calls, same
    testable-without-running-the-app pattern as the footnote builder.
    """
    a2 = record["agents"]["agent2"]
    semantic_citation = a2.get("semantic_top_citation")
    lexical_citation = a2.get("lexical_top_citation")

    # Phase 7 tickets (internal build terminology -- never shown to a
    # dashboard reader) predate the retrieval architecture entirely -- Agent
    # 2 researched from its own knowledge with no search behind it at all,
    # so labelling them "Lexical only" would imply a search step that never
    # ran.
    if not semantic_citation and not lexical_citation:
        return (
            '<span class="retrieval-pre-rag" title="This ticket was decided before the retrieval system '
            "existed -- Agent 2 researched from its own knowledge, with no keyword or embedding search "
            'behind it.">No retrieval used</span>'
        )

    if not semantic_citation:
        return (
            '<span class="retrieval-lexical" title="Only the keyword-based regulation search ran for this '
            'ticket — the AI-embedding-based search is Product-path-only.">Lexical only</span>'
        )

    candidate_detail = f'<div class="retrieval-detail">Lexical: {lexical_citation or "(no match)"}<br>Semantic: {semantic_citation}</div>'
    citation = a2["output"].get("citation")
    outside_corpus = a2.get("outside_cached_corpus")
    ungrounded = a2.get("citation_not_in_retrieval")

    if citation and (outside_corpus or ungrounded):
        reason = (
            "Agent 2 flagged this citation as outside this system's cached regulation corpus"
            if outside_corpus
            else "Agent 2's citation doesn't match what either retrieval tool actually surfaced"
        )
        return (
            f'<span class="retrieval-flagged-badge" title="{reason} — routed for human review.">Flagged</span>'
            f"{candidate_detail}"
        )

    # Defensive fallback, not currently reachable in this data: every
    # Product-path ticket today has had citation_not_in_retrieval computed
    # (retroactively, for the four that predate the Phase 9 restructure --
    # see the backfill note in the sheet update history). If a future record
    # somehow arrives with a citation but neither grounding field ever
    # computed, defaulting it to "Grounded" would be a false claim of
    # verification that never happened -- so this stays a distinct,
    # deliberately unverified-looking state instead.
    if citation and outside_corpus is None and ungrounded is None:
        return (
            '<span class="retrieval-lexical" title="This ticket\'s citation was never checked against what '
            'retrieval surfaced.">Not verified</span>'
            f"{candidate_detail}"
        )

    if citation:
        return (
            '<span class="retrieval-grounded" title="Agent 2 cited a regulation, and it matches a candidate '
            'retrieval (keyword and/or embedding search) actually surfaced.">Grounded</span>'
            f"{candidate_detail}"
        )

    return (
        '<span class="retrieval-none-applicable" title="Retrieval surfaced candidate regulations, but Agent 2 '
        "judged none of them actually applied to this complaint's facts.\">No regulation applies</span>"
        f"{candidate_detail}"
    )


# Explains the Retrieval column's states in plain text, not just an
# on-hover tooltip -- a reader skimming the table has no reason to know to
# hover, so the tooltips on each badge (see retrieval_badge_html) are a
# bonus for anyone who does, not the only explanation available.
RETRIEVAL_COLUMN_CAPTION = (
    '<p class="section-caption">Retrieval: for Product-path tickets, two independent tools search for the '
    "applicable regulation — a keyword-based lookup and an AI-embedding-based one — and Agent 2 grounds its "
    "citation in what they found. <strong>Grounded</strong> means the citation matches a retrieved candidate; "
    "<strong>No regulation applies</strong> means Agent 2 judged none of the candidates fit; "
    "<strong>Flagged</strong> means Agent 2 cited something retrieval couldn't verify, routed for human review; "
    "<strong>No retrieval used</strong> means this ticket was decided before the retrieval system existed.</p>"
)


def kpi_missed_risk_rate(records):
    """Replaces the old blended "escalation agreement" framing. That number
    averaged two very different things into one percentage: cases where we
    escalated something CFPB's own outcome record calls routine (extra
    caution — not a miss), and cases where CFPB's record shows something
    genuinely happened (an untimely response, or monetary relief paid) but
    we auto-resolved anyway (a real miss). Blending them produced a bare
    percentage that read as an accuracy score even with a caveat underneath
    it, which is a misleading headline number regardless of the caption.

    This KPI reports only the second, compliance-relevant question: of the
    tickets CFPB's own record flags as elevated, what share did we let
    through without a human ever reviewing it? The other side (extra
    caution beyond CFPB's record) is reported separately, in its own
    footnote below the KPI row -- see build_escalation_caution_footnote_html.
    """
    with_gt = [r for r in records if r.get("ground_truth")]
    elevated = [r for r in with_gt if r["ground_truth"]["ground_truth_signal"] == "elevated"]
    if not elevated:
        return None, "No CFPB-flagged-elevated tickets in this data yet"
    missed = sum(1 for r in elevated if r["decision"] == "AUTO_RESOLVE")
    pct = round(100 * missed / len(elevated))
    ticket_word = "ticket" if len(elevated) == 1 else "tickets"
    # States the outcome directly rather than as a bare "0/1" fraction --
    # confirmed by user feedback that a 0-over-N ratio makes a reader do the
    # subtraction to realize it's good news, especially at small n.
    if missed == 0:
        sub = f"{len(elevated)} of {len(elevated)} CFPB-flagged-elevated {ticket_word} correctly escalated for review"
    else:
        sub = f"{missed} of {len(elevated)} CFPB-flagged-elevated {ticket_word} auto-resolved without human review"
    return pct, sub


def build_escalation_caution_footnote_html(records):
    """The other half of the comparison kpi_missed_risk_rate deliberately
    excludes: tickets escalated even though CFPB's own outcome record reads
    as routine. Reported here as its own line, not folded back into a
    single percentage -- these are the pipeline erring toward caution on a
    low-confidence draft, a factual conflict, or a repeat-complaint
    pattern, not a disagreement with what actually happened.
    """
    with_gt = [r for r in records if r.get("ground_truth")]
    routine = [r for r in with_gt if r["ground_truth"]["ground_truth_signal"] == "routine"]
    if not routine:
        return ""
    extra_caution = [r for r in routine if r["decision"] == "ESCALATE_TO_HUMAN"]
    if not extra_caution:
        return (
            '<p class="section-caption">Every CFPB-flagged-routine ticket in this data was also '
            "auto-resolved — no extra-caution escalations to report yet.</p>"
        )
    return (
        f'<p class="section-caption"><strong>{len(extra_caution)}/{len(routine)}</strong> tickets CFPB\'s own '
        "outcome record reads as routine were escalated to a human anyway — the pipeline erring toward "
        "caution (a low-confidence draft, a factual conflict, a repeat-complaint pattern), not a "
        "disagreement with what actually happened.</p>"
    )


def kpi_category_agreement(records):
    # Real, computed: does Agent 1's classified issue match what the
    # consumer actually filed with CFPB, at either the issue or sub-issue
    # level (Ticket C's classification lands at the sub-issue level, since
    # that's the substantive category for that compound ticket -- see
    # spec Section 6).
    if not records:
        return None, "No classifications yet"
    matches = 0
    for r in records:
        out = r["agents"]["agent1"]["output"] or {}
        classified = out.get("primary_issue") or out.get("issue")
        if classified and classified in (r.get("issue"), r.get("sub_issue")):
            matches += 1
    pct = round(100 * matches / len(records))
    return pct, f"{matches}/{len(records)} match CFPB's own filed product/issue category"


def render_kpi_card(col, label, value, sub):
    with col:
        if value is None:
            value_html = '<div class="kpi-value pending">Awaiting timed run</div>'
            sub_html = f'<div class="kpi-sub">{sub}</div>'
        else:
            value_html = f'<div class="kpi-value">{value}%</div>'
            sub_html = f'<div class="kpi-sub">{sub}</div>'
        md_html(
            f"""
            <div class="kpi-card">
                <div class="kpi-label">{label}</div>
                {value_html}
                {sub_html}
            </div>
            """
        )


# ---------------------------------------------------------------------------
# Charts
# ---------------------------------------------------------------------------
def chart_decision_breakdown(records):
    counts = {"Escalated to human": 0, "Auto-resolved": 0}
    for r in records:
        if r["decision"] == "ESCALATE_TO_HUMAN":
            counts["Escalated to human"] += 1
        else:
            counts["Auto-resolved"] += 1
    fig = go.Figure(
        go.Bar(
            x=list(counts.keys()),
            y=list(counts.values()),
            marker_color=[NAVY, "#94A3B8"],
            text=list(counts.values()),
            textposition="outside",
            width=0.5,
        )
    )
    fig.update_layout(yaxis=dict(dtick=1))
    return plotly_brand_layout(fig, "Escalate vs. auto-resolve")


def chart_category_breakdown(records, selected=None):
    counts = {}
    for r in records:
        counts[r["product"]] = counts.get(r["product"], 0) + 1
    labels = list(counts.keys())
    base_colors = dict(zip(labels, CHART_SERIES))
    # PREVIEW ONLY (not yet wired to KPIs/other charts/tables): dims any
    # category not in `selected` -- empty/None selected means "all", so
    # nothing dims.
    if selected:
        colors = [base_colors[l] if l in selected else LIGHT_GREY for l in labels]
    else:
        colors = [base_colors[l] for l in labels]
    fig = go.Figure(
        go.Pie(
            labels=labels,
            values=list(counts.values()),
            marker=dict(colors=colors),
            hole=0.55,
            textfont=dict(family="Inter, sans-serif"),
        )
    )
    return plotly_brand_layout(fig, "Product category breakdown")


def chart_confidence_distribution(records):
    fig = go.Figure()
    for i, agent_key in enumerate(["agent1", "agent4"]):
        agent_num = 1 if agent_key == "agent1" else 4
        label = f"Agent {agent_num}"
        values, labels = [], []
        for r in records:
            out = r["agents"][agent_key]["output"] or {}
            conf = out.get("confidence")
            if conf is None and "issues" in out:
                # Ticket C's multi-issue schema: use the primary issue's confidence.
                primary = next((i for i in out["issues"] if i["issue"] == out.get("primary_issue")), None)
                conf = primary["confidence"] if primary else None
            if conf is not None:
                values.append(conf)
                labels.append(r["complaint_id"])
        fig.add_trace(go.Bar(name=label, x=labels, y=values, marker_color=CHART_SERIES[i]))
    # complaint_id ("9999970") reads as numeric to Plotly's default axis-type
    # inference, which formats it with an SI suffix ("9.99997M") -- force a
    # categorical axis so it prints as the literal ID.
    fig.update_layout(barmode="group", yaxis=dict(range=[0, 1], title="confidence"), xaxis=dict(type="category"))
    return plotly_brand_layout(fig, "Agent confidence by ticket")


def chart_tool_use_frequency(records):
    tool_labels = {
        "agent1": "Agent 1: taxonomy lookup",
        "agent2_regulation": "Agent 2: regulation index (always)",
        "agent2_crm": "Agent 2: broader CRM lookup",
        "agent3": "Agent 3: exact clause fetch",
        "agent4": "Agent 4: re-verify",
    }
    counts = {k: 0 for k in tool_labels}
    for r in records:
        a = r["agents"]
        if a["agent1"]["tool_used"]:
            counts["agent1"] += 1
        counts["agent2_regulation"] += 1  # always runs, spec Section 6
        if a["agent2"]["broader_crm_lookup_used"]:
            counts["agent2_crm"] += 1
        if a["agent3"]["tool_used"]:
            counts["agent3"] += 1
        if a["agent4"]["tool_used"]:
            counts["agent4"] += 1
    n = len(records)
    fig = go.Figure(
        go.Bar(
            y=[tool_labels[k] for k in tool_labels],
            x=[counts[k] for k in tool_labels],
            orientation="h",
            marker_color=NAVY,
            text=[f"{counts[k]}/{n}" for k in tool_labels],
            textposition="outside",
            # Without this, an "outside" text label on a bar that reaches (or
            # comes close to) the axis's own upper bound gets clipped to the
            # plotting rectangle -- visible once a tool hits n/n (e.g. Agent
            # 2's regulation-index lookup, which always runs). The extra
            # range headroom below is for visual balance, not clipping --
            # cliponaxis is what actually fixes the cutoff.
            cliponaxis=False,
        )
    )
    fig.update_layout(xaxis=dict(range=[0, n + 1.5], dtick=1), margin=dict(l=190))
    return plotly_brand_layout(fig, "Tool-use frequency (of tickets processed)")


# ---------------------------------------------------------------------------
# Full-draft popup -- the queue tables below only ever show a truncated
# preview (keeps the table scannable at a glance). Clicking that preview
# opens the complete text here instead. The click itself is a plain browser
# navigation to `?view_draft=<complaint_id>` (same mechanism as the
# queue_view bar-jump links above -- see main()'s handling of it), not a
# Streamlit widget, since a custom HTML table cell can't carry a widget
# callback directly.
# ---------------------------------------------------------------------------
@st.dialog("Full draft", width="large")
def show_full_draft_dialog(complaint_id, company, draft_text):
    st.markdown(f"**{complaint_id} — {company}**")
    st.markdown(draft_text.replace("\n", "  \n") if draft_text else "*(no draft text)*")


def draft_text_of(record):
    return (record["agents"]["agent3"]["output"] or {}).get("draft") or record.get("draft") or ""


def draft_preview_of(draft, max_len=110):
    # Collapses newlines/whitespace to single spaces before truncating --
    # a raw "\n\n" surviving inside the <a> tag below breaks Streamlit's
    # markdown-to-HTML pass (a blank line inside inline HTML gets read as a
    # paragraph break, splitting one anchor into two real DOM elements;
    # confirmed live before this fix, not a hypothetical). A collapsed,
    # single-line snippet is also just a cleaner table preview either way.
    collapsed = " ".join(draft.split())
    return (collapsed[:max_len] + "…") if len(collapsed) > max_len else collapsed


def draft_preview_link_html(record, preview_text, queue_view):
    href = f"?view_draft={quote(record['complaint_id'])}&queue_view={quote(queue_view)}#queue-section"
    return f'<a href="{href}" target="_self" class="draft-preview-link" title="Click to read the full draft">{preview_text}</a>'


# ---------------------------------------------------------------------------
# Queue table -- drafts awaiting human review.
# ---------------------------------------------------------------------------
def render_queue_table(records):
    # Records have no date_received of their own (see export_dashboard_data.mjs's
    # comment on the flattened shape) -- their position in the array IS
    # chronological order (append-only Sheet writes / simulator's fixture
    # order), so reversing it is what "latest ticket first" means here.
    escalated = [r for r in reversed(records) if r["decision"] == "ESCALATE_TO_HUMAN"]
    heading = "#### Queue: drafts awaiting human review"
    if not escalated:
        md_html(f'{heading}\n<p class="section-caption">No tickets currently awaiting human review.</p>')
        return

    rows = []
    for r in escalated:
        draft = draft_text_of(r)
        draft_preview = draft_preview_of(draft)
        draft_link = draft_preview_link_html(r, draft_preview, "Escalated to human")
        reason = (r["agents"]["agent4"]["output"] or {}).get("reason", "")
        confidence = (r["agents"]["agent4"]["output"] or {}).get("confidence")
        retrieval = retrieval_badge_html(r)
        rows.append(
            f"""
            <tr>
                <td class="mono">{r['complaint_id']}</td>
                <td>{r['company']}</td>
                <td>{r['issue']}</td>
                <td>{retrieval}</td>
                <td>{draft_link}</td>
                <td>{confidence:.2f}</td>
                <td>{reason}</td>
            </tr>
            """
        )

    md_html(
        f"""
        {heading}
        {RETRIEVAL_COLUMN_CAPTION}
        <table class="queue-table">
            <thead>
                <tr>
                    <th>Complaint ID</th><th>Company</th><th>Issue</th><th>Retrieval</th>
                    <th>Draft (click to read in full)</th><th>QA confidence</th><th>Escalation reason</th>
                </tr>
            </thead>
            <tbody>{''.join(rows)}</tbody>
        </table>
        """
    )


def render_auto_resolved_table(records):
    # See render_queue_table's comment: array position is chronological order.
    auto_resolved = [r for r in reversed(records) if r["decision"] == "AUTO_RESOLVE"]
    heading = "#### Queue: auto-resolved tickets"
    if not auto_resolved:
        md_html(
            f"""
            {heading}
            <p class="section-caption">No tickets have auto-resolved yet — this table will populate
            automatically as soon as one does.</p>
            """
        )
        return

    rows = []
    for r in auto_resolved:
        draft = draft_text_of(r)
        draft_preview = draft_preview_of(draft)
        draft_link = draft_preview_link_html(r, draft_preview, "Auto-resolved")
        confidence = (r["agents"]["agent4"]["output"] or {}).get("confidence")
        confidence_str = f"{confidence:.2f}" if confidence is not None else "—"
        retrieval = retrieval_badge_html(r)
        rows.append(
            f"""
            <tr>
                <td class="mono">{r['complaint_id']}</td>
                <td>{r['company']}</td>
                <td>{r['issue']}</td>
                <td>{retrieval}</td>
                <td>{draft_link}</td>
                <td>{confidence_str}</td>
            </tr>
            """
        )

    md_html(
        f"""
        {heading}
        {RETRIEVAL_COLUMN_CAPTION}
        <table class="queue-table">
            <thead>
                <tr>
                    <th>Complaint ID</th><th>Company</th><th>Issue</th><th>Retrieval</th>
                    <th>Draft (click to read in full)</th><th>QA confidence</th>
                </tr>
            </thead>
            <tbody>{''.join(rows)}</tbody>
        </table>
        """
    )


# ---------------------------------------------------------------------------
# Agent legend -- what "Agent 1/2/3/4" mean, spec Section 6. Rendered as a
# persistent reference at the top of the Technical detail tab rather than
# relying on chart hover text, which a viewer has no reason to discover on
# their own.
# ---------------------------------------------------------------------------
def render_agent_legend():
    cards = "".join(
        f"""
        <div class="agent-card">
            <div class="agent-card-num">Agent {num}</div>
            <div class="agent-card-name">{info['name']}</div>
            <div class="agent-card-tool">Tool: {info['tool']}</div>
            <div class="agent-card-when">{info['used_when']}</div>
        </div>
        """
        for num, info in AGENT_INFO.items()
    )
    md_html(f'<div class="agent-legend">{cards}</div>')


# ---------------------------------------------------------------------------
# Page
# ---------------------------------------------------------------------------
def main():
    inject_brand_css()
    log = load_pipeline_log()

    st.markdown("## Complaint Triage Orchestrator")
    st.markdown(
        '<p class="section-caption">Real CFPB complaint data + real federal regulation text + a disclosed '
        "synthetic CRM layer, triaged by four conditional-tool-use agents behind a deterministic escalation "
        "gate.</p>",
        unsafe_allow_html=True,
    )

    if log is None:
        st.warning(
            f"No pipeline data found at `{DATA_PATH}`. Run `node scripts/export_dashboard_data.mjs` "
            "from the repo root first."
        )
        render_disclosure_banner()
        return

    records = log["records"]

    # Category filter: single source of truth for both tabs. Read directly
    # from session_state rather than the st.multiselect(...) call itself,
    # since that widget is declared further down (inside tab_overview) but
    # this value is also needed here, before st.tabs() runs, for the
    # Technical detail tab's dynamic label -- a keyed widget's session_state
    # slot is already updated by the time the script re-runs, regardless of
    # where in the script the widget itself is declared.
    categories = []
    seen_categories = set()
    for r in records:
        p = r["product"]
        if p not in seen_categories:
            seen_categories.add(p)
            categories.append(p)
    st.session_state.setdefault("category_filter_multiselect", [])
    selected_categories = set(st.session_state.category_filter_multiselect)
    filtered_records = [r for r in records if r["product"] in selected_categories] if selected_categories else records

    technical_label = "Technical detail"
    if selected_categories:
        # Stable order matching the chart/legend/dropdown (categories'
        # own insertion order), not sorted() or set iteration order.
        technical_label = f"Technical detail ({', '.join(c for c in categories if c in selected_categories)})"

    # Seeds the queue-view toggle from a `?queue_view=...` URL query param --
    # must happen before st.segmented_control(key="queue_view") instantiates
    # below, since a keyed widget's session_state entry, once set, wins over
    # `default` on every later rerun. Only applied once per session (real
    # navigations from the bar-jump links below create a fresh session
    # anyway); a manual toggle click after that always takes priority.
    scroll_to_queue = False
    if "queue_view" not in st.session_state:
        requested_view = st.query_params.get("queue_view")
        if requested_view in ("Escalated to human", "Auto-resolved"):
            st.session_state["queue_view"] = requested_view
            scroll_to_queue = True
        else:
            # Same value segmented_control's own `default` would have used --
            # set directly instead of passing `default=` alongside a keyed
            # widget that Session State already governs, which Streamlit
            # warns is a conflicting/undefined combination.
            st.session_state["queue_view"] = "Escalated to human"

    # Opens the full-draft popup when a draft preview link above was clicked
    # (a real navigation to `?view_draft=<complaint_id>`, same mechanism as
    # queue_view). Cleared immediately, unlike queue_view -- this is a
    # one-time reaction to the click that led here, not state that should
    # keep re-opening the dialog on every later, unrelated rerun (e.g.
    # changing the category filter).
    requested_draft_id = st.query_params.get("view_draft")
    if requested_draft_id:
        del st.query_params["view_draft"]
        match = next((r for r in records if r["complaint_id"] == requested_draft_id), None)
        if match:
            show_full_draft_dialog(match["complaint_id"], match["company"], draft_text_of(match))

    tab_overview, tab_technical = st.tabs(["Overview", technical_label])

    with tab_overview:
        is_live = log.get("_meta", {}).get("records_source") == "google_sheets_live"
        data_source_note = (
            "Data source: live Google Sheet, re-checked every 5 minutes."
            if is_live
            else "Data source: static snapshot (no live Google credential configured for this deployment — "
            "see the README's \"Live dashboard data source\" section)."
        )
        if len(records) < 50:
            st.markdown(
                f'<p class="section-caption"><strong>{len(records)} ticket(s) processed to date.</strong> '
                "This is an early-stage pilot, so the sample is intentionally small — every record here "
                "reflects a genuine pipeline decision, drawn from hand-verified test cases and live tickets "
                "processed since. The dashboard updates automatically as more tickets come in. "
                f"{data_source_note}</p>",
                unsafe_allow_html=True,
            )

        cols = st.columns(5)
        hs_val, hs_sub = kpi_hours_saved()
        render_kpi_card(cols[0], "Hours saved / ticket", hs_val, hs_sub)
        ca_val, ca_sub = kpi_citation_accuracy(filtered_records)
        render_kpi_card(cols[1], "Citation accuracy", ca_val, ca_sub)
        sla_val, sla_sub = kpi_sla_compliance()
        render_kpi_card(cols[2], "SLA compliance", sla_val, sla_sub)
        mr_val, mr_sub = kpi_missed_risk_rate(filtered_records)
        render_kpi_card(cols[3], "Missed-risk rate", mr_val, mr_sub)
        cat_val, cat_sub = kpi_category_agreement(filtered_records)
        render_kpi_card(cols[4], "Category agreement", cat_val, cat_sub)

        md_html(build_escalation_caution_footnote_html(filtered_records))
        render_retrieval_grounding_footnote(filtered_records)

        st.markdown("<br>", unsafe_allow_html=True)

        # Category filter (categories/selected_categories/filtered_records
        # computed earlier, before st.tabs()). Native Plotly click-to-select
        # on the donut was tried and ruled out first: 0/5 real slice clicks
        # registered a selection, and legend clicks are pure client-side
        # trace-visibility toggles that never reach Streamlit's selection
        # state at all -- worse than the bar chart's already-flaky results.
        # This multiselect is a real, guaranteed-to-register widget instead.
        #
        # Positioned above both charts, not tucked under the donut: this is
        # the primary filter (pick a category), with the escalate/auto-
        # resolve bars beside the donut as the secondary filter within it --
        # top-to-bottom placement matches that selection order.
        st.multiselect(
            "Filter by product category", options=categories, key="category_filter_multiselect",
            placeholder="All categories shown — select to filter",
        )

        left, right = st.columns(2)
        with left:
            # Deliberately built from the unfiltered `records`, with only the
            # selected slice(s) at full color and the rest dimmed -- this
            # chart IS the filter control, so it shows the whole picture with
            # the current selection highlighted, not a recomputed subset.
            st.plotly_chart(chart_category_breakdown(records, selected_categories), width='stretch')
        with right:
            # A Plotly bar-click -> table-jump interaction was tried first via
            # st.plotly_chart(..., on_select="rerun") and dropped after it
            # proved flaky under real clicks (re-verified live: sometimes a
            # click's selection state didn't land until the NEXT click,
            # sometimes it silently reset to empty -- inconsistent is worse
            # than a clean failure, and the flakiness is in Streamlit's
            # Python-JS selection bridge, not Plotly's own rendering.
            # A plain HTML <a href="?queue_view=...#queue-section"> overlay,
            # positioned over each bar with a keyed st.container for CSS
            # scoping, sidesteps that bridge entirely -- it's a real browser
            # navigation with a query param + anchor, not a Streamlit rerun
            # event. `main()` seeds st.session_state["queue_view"] from
            # st.query_params before the segmented_control below is
            # instantiated, so this and the manual toggle both drive the same
            # single source of truth.
            with st.container(key="decision_chart_wrap"):
                st.plotly_chart(chart_decision_breakdown(filtered_records), width='stretch')
                st.markdown(
                    """
                    <style>
                    .st-key-decision_chart_wrap { position: relative; }
                    /* Streamlit wraps every element (including this markdown
                       call) in its own position:relative, height:0 container
                       -- that becomes the nearest positioned ancestor and
                       steals the containing-block role before top/bottom %
                       can resolve against the wrapper above. Neutralize it. */
                    .st-key-decision_chart_wrap .stElementContainer { position: static; }
                    .st-key-decision_chart_wrap .bar-jump-link {
                        position: absolute; top: 14%; bottom: 10%;
                        border-radius: 6px; cursor: pointer;
                    }
                    .st-key-decision_chart_wrap .bar-jump-link:hover { background: rgba(21, 62, 117, 0.08); }
                    .st-key-decision_chart_wrap .bar-jump-left { left: 2%; width: 44%; }
                    .st-key-decision_chart_wrap .bar-jump-right { right: 2%; width: 44%; }
                    </style>
                    <a class="bar-jump-link bar-jump-left" title="Jump to: drafts awaiting human review"
                       href="?queue_view=Escalated+to+human#queue-section"></a>
                    <a class="bar-jump-link bar-jump-right" title="Jump to: auto-resolved tickets"
                       href="?queue_view=Auto-resolved#queue-section"></a>
                    """,
                    unsafe_allow_html=True,
                )

        st.markdown('<div id="queue-section"></div>', unsafe_allow_html=True)
        if scroll_to_queue:
            # st.markdown-injected <script> tags don't execute in Streamlit
            # (HTML is set via innerHTML, not parsed as live markup) --
            # components.v1.html runs in a real iframe, where they do. The
            # anchor in the bar-jump links' href can't do this alone: the
            # browser tries to jump to #queue-section on initial page load,
            # before Streamlit has finished rendering that element, so the
            # native jump silently misses. This polls for it instead.
            #
            # Streamlit nudges toward st.iframe as the replacement here, but
            # that only takes a `src` URL, not raw HTML/JS content -- not a
            # substitute for what this actually needs.
            components.html(
                """
                <script>
                (function () {
                    let tries = 0;
                    const tryScroll = () => {
                        const el = window.parent.document.getElementById("queue-section");
                        if (el) {
                            el.scrollIntoView({behavior: "smooth", block: "start"});
                        } else if (tries++ < 30) {
                            setTimeout(tryScroll, 100);
                        }
                    };
                    tryScroll();
                })();
                </script>
                """,
                height=0,
            )
        with st.container(key="queue_card"):
            queue_view = st.segmented_control(
                "Queue view", ["Escalated to human", "Auto-resolved"],
                key="queue_view", label_visibility="collapsed",
            )
            if queue_view == "Auto-resolved":
                render_auto_resolved_table(filtered_records)
            else:
                render_queue_table(filtered_records)

    with tab_technical:
        st.markdown(
            '<p class="section-caption">Agent-level detail, kept separate from the business-facing '
            "overview above.</p>",
            unsafe_allow_html=True,
        )
        render_agent_legend()
        left, right = st.columns(2)
        with left:
            st.plotly_chart(chart_confidence_distribution(filtered_records), width='stretch')
        with right:
            st.plotly_chart(chart_tool_use_frequency(filtered_records), width='stretch')

        st.markdown("#### Raw pipeline log")
        st.dataframe(pd.json_normalize(filtered_records), width='stretch', height=300)

        with st.expander("Other disclosures"):
            st.markdown(
                "- Real, live, government-verified complaints against named real companies — "
                "independent portfolio analysis, not affiliated with or endorsed by any company named in the data.\n"
                "- Missed-risk rate, category agreement, and similar outcome-comparison metrics are directional "
                "signals, not certified accuracy.\n"
                "- Policy citations reference real federal regulation; this is a technical demonstration, "
                "not legal advice."
            )

    render_disclosure_banner()


def render_disclosure_banner():
    st.markdown(
        '<div class="disclosure-banner">Customer/account records shown here are <strong>synthetic</strong> '
        "— generated to demonstrate the pipeline, not real customer data. "
        "servicemember_flag and special_population_flag carry forward CFPB's own real tags field where present; "
        "everything else in the CRM record is synthetic.</div>",
        unsafe_allow_html=True,
    )


if __name__ == "__main__":
    main()
