/**
 * Generates dashboard/data/pipeline_log.json -- the Streamlit dashboard's only
 * data source (spec Section 15 Phase 6).
 *
 * Reuses scripts/simulate_workflow.mjs's execute(), which runs the ACTUAL
 * committed n8n workflow JSON node-by-node. This script does not duplicate any
 * agent/escalation/ground-truth logic -- it just runs the real workflow and
 * writes out what came back.
 *
 * Why only 3 records: Phase 7 (the mock-to-real Claude API swap) hasn't
 * happened yet, so the only tickets with a genuine, fully-processed pipeline
 * decision are the three Section 6 fixtures -- every live ticket the
 * Schedule/Manual trigger path fetches still dead-ends at "Live Ticket
 * (Awaiting Phase 7)" (spec Section 15 Phase 3/7). This script does not pad
 * the log with synthetic extra tickets to make dashboard charts look fuller;
 * the dashboard is built to read this exact shape and be honest about n=3
 * until a real pilot run accumulates more.
 *
 * Output format is deliberately close to what spec Section 11's Google Sheets
 * store would eventually hold, so swapping the dashboard's data source from
 * this local file to a live Sheets read later is a small, isolated change --
 * not a redesign.
 *
 * Run: node scripts/export_dashboard_data.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execute } from "./simulate_workflow.mjs";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT_PATH = path.join(REPO_ROOT, "dashboard/data/pipeline_log.json");

function main() {
  const results = execute("Fixture Test Trigger (A/B/C)", [{}]);
  const escalated = results["Final: Escalate to Human Queue"] || [];
  const autoResolved = results["Final: Auto-Resolve"] || [];

  const records = [...escalated, ...autoResolved].map((r) => ({ ...r, source: "pilot_fixture" }));
  // Stable order: chronological by the real date_received timestamps
  // (spec v11 Section 3a) -- C (22:07) -> A (22:24) -> B (22:28).
  const order = { "9999983": 0, "9999970": 1, "9999975": 2 };
  records.sort((a, b) => (order[a.complaint_id] ?? 99) - (order[b.complaint_id] ?? 99));

  const log = {
    _meta: {
      description: "Pipeline decision log -- spec Section 15 Phase 5/6. Generated by scripts/export_dashboard_data.mjs from the real, committed n8n workflow JSON (via scripts/simulate_workflow.mjs), not hand-written.",
      generated_at: new Date().toISOString(),
      record_count: records.length,
      scope_note: "Only the three Section 6 fixture tickets have a genuine pipeline decision as of this build (Phase 7's mock-to-real Claude API swap hasn't happened yet). This is not a sampled subset of a larger dataset -- it is the complete set of tickets this pipeline has ever actually decided on.",
    },
    records,
  };

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, JSON.stringify(log, null, 2) + "\n", "utf-8");
  console.log(`Wrote ${OUT_PATH} (${records.length} records: ${escalated.length} escalated, ${autoResolved.length} auto-resolved)`);
}

main();
