/**
 * Generates dashboard/data/pipeline_log.json -- the Streamlit dashboard's only
 * data source (spec Section 15 Phase 6).
 *
 * Reuses scripts/simulate_workflow.mjs's execute(), which runs the ACTUAL
 * committed n8n workflow JSON node-by-node. This script does not duplicate any
 * agent/escalation/ground-truth logic -- it just runs the real workflow and
 * writes out what came back.
 *
 * Two separate arrays in the output, never merged:
 *   - `records`: tickets with a genuine, fully-processed pipeline DECISION.
 *     As of this build that's exactly the three Section 6 fixtures -- Phase
 *     3's mock agents only have fixture data for Tickets A/B/C. Every KPI
 *     and chart in the dashboard is computed from this array only.
 *   - `awaiting_records`: real tickets fetched live from CFPB (Phase 1's
 *     actual HTTP call) and given a real synthetic CRM record (Phase 2),
 *     but with NO agent decision -- no severity, no draft, no escalation
 *     call. Real ticket data, honestly labeled as undecided, kept
 *     completely separate so it can never accidentally feed a KPI.
 *
 * Output format for `records` is deliberately close to what spec Section
 * 11's Google Sheets store would eventually hold, so swapping the
 * dashboard's data source from this local file to a live Sheets read later
 * is a small, isolated change -- not a redesign.
 *
 * Usage:
 *   node scripts/export_dashboard_data.mjs
 *     Regenerates `records` from the fixtures (fast, no network call).
 *     Leaves `awaiting_records` as whatever was already in the file --
 *     does NOT silently re-fetch or wipe it.
 *   node scripts/export_dashboard_data.mjs --live-batch
 *     Also runs the real live trigger path (a real CFPB API call, capped at
 *     25 per spec Section 5) and replaces `awaiting_records` with that
 *     fresh batch.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execute } from "./simulate_workflow.mjs";

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const OUT_PATH = path.join(REPO_ROOT, "dashboard/data/pipeline_log.json");
const INCLUDE_LIVE_BATCH = process.argv.includes("--live-batch");

async function main() {
  const { trace } = await execute("Fixture Test Trigger (A/B/C)", [{}]);
  const escalated = trace["Final: Escalate to Human Queue"] || [];
  const autoResolved = trace["Final: Auto-Resolve"] || [];

  const records = [...escalated, ...autoResolved].map((r) => ({ ...r, source: "pilot_fixture" }));
  // Stable order: chronological by the real date_received timestamps (the
  // final record shape doesn't carry date_received, so this is a lookup
  // table into FIXTURE_TICKETS's own order rather than a live sort) --
  // C (2024-09-03T22:07) -> A (22:24) -> B (22:28) -> F (2026-07-14T00:02)
  // -> G (00:03) -> I (00:04) -> J (00:06) -> H (00:11) -> D (00:13) -> E (00:17).
  const order = { "9999983": 0, "9999970": 1, "9999975": 2, "24157473": 3, "24157200": 4, "24157195": 5, "24157240": 6, "24157609": 7, "24158082": 8, "24157871": 9 };
  records.sort((a, b) => (order[a.complaint_id] ?? 99) - (order[b.complaint_id] ?? 99));

  // Preserve whatever live batch already exists unless explicitly asked to
  // refresh it -- a routine "I changed the workflow, regenerate the fixture
  // records" run shouldn't silently make a network call or wipe real data
  // that was deliberately fetched earlier.
  let awaitingRecords = [];
  if (fs.existsSync(OUT_PATH)) {
    try {
      awaitingRecords = JSON.parse(fs.readFileSync(OUT_PATH, "utf-8")).awaiting_records || [];
    } catch {
      awaitingRecords = [];
    }
  }

  if (INCLUDE_LIVE_BATCH) {
    const liveRun = await execute("Manual Trigger", [{}]);
    awaitingRecords = (liveRun.terminal["Live Ticket (Awaiting Phase 7)"] || []).map((r) => ({ ...r, source: "live_fetch" }));
  }

  const log = {
    _meta: {
      description: "Pipeline decision log -- spec Section 15 Phase 5/6. Generated by scripts/export_dashboard_data.mjs from the real, committed n8n workflow JSON (via scripts/simulate_workflow.mjs), not hand-written.",
      generated_at: new Date().toISOString(),
      record_count: records.length,
      awaiting_record_count: awaitingRecords.length,
      scope_note: "records: tickets with a genuine pipeline decision -- only the three Section 6 fixtures as of this build (Phase 7's mock-to-real Claude API swap hasn't happened yet). awaiting_records: real tickets fetched live from CFPB with a real synthetic CRM record but NO agent decision -- kept fully separate so KPIs are never computed from undecided tickets.",
    },
    records,
    awaiting_records: awaitingRecords,
  };

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, JSON.stringify(log, null, 2) + "\n", "utf-8");
  console.log(`Wrote ${OUT_PATH} (${records.length} decided records: ${escalated.length} escalated, ${autoResolved.length} auto-resolved; ${awaitingRecords.length} awaiting-Phase-7 records${INCLUDE_LIVE_BATCH ? " -- refreshed via live fetch" : " -- carried forward, not refreshed"})`);
}

main().catch((err) => {
  console.error("EXPORT FAILED:", err);
  process.exit(1);
});
